### ISSUE TITLE
Pistons interact with leaves Incorrectly

### ISSUE THREAD

**Issue by Laserlance141** [GingerWalnut/SQBeyondPublic#100]
Basically, when a piston pushes a leaf block, the leaf block is suppose to break. For some reason, now it doesn't. Makes auto tree-farms impossible, as they rely on leaves being broken by pistons.
![2019-03-02_22 17 47](https://user-images.githubusercontent.com/13091148/53691761-6fd26380-3d39-11e9-978d-7ec55a1d8103.png)
![2019-03-02_22 18 00](https://user-images.githubusercontent.com/13091148/53691762-719c2700-3d39-11e9-90ec-7425ecda6e87.png)

**Comment by GingerWalnut** [comment]
Fixed
