### ISSUE TITLE
Map not updating

### ISSUE THREAD

**Issue by Elttob** [GingerWalnut/SQBeyondPublic#101]
The dynamic map is still showing stuff from the beta. Here's my beta house, screenshot taken just now:
![image](https://user-images.githubusercontent.com/11815374/53696392-6b03c300-3dbe-11e9-9cfd-dc19e0621dbf.png)

Chunks I have built in aren't re-rendering on the map either.

**Comment by GingerWalnut** [comment]
Unfortunately, we would have to re-render all of the dynmaps to achieve this.
