### ISSUE TITLE
Piracy Contract Bug

### ISSUE THREAD

**Issue by FlyingTaurus523** [GingerWalnut/SQBeyondPublic#105]
You are able to right click on a data core multiple times to redeem the same amount of blocks over and over again for Skydogs contracts.

**Comment by GingerWalnut** [comment]
Fixed for next restart

**Comment by OldDewd** [comment]
skydogs contact no longer visible.. only the pirate captain and he can't be accessed.. he's inside the stone portion, no other contacts visible anywhere else on the asteroid.

**Comment by OldDewd** [comment]
wasted a long flight to find out I can't do anything there r/n.  :(  Pls fix. :D

**Comment by GingerWalnut** [comment]
This has been fixed. In the future, please open a new bug report instead of posting on an old one.
