### ISSUE TITLE
Crash when shot at (By Laser from what I can tell) 

### ISSUE THREAD

**Issue by Crimsonknight3** [GingerWalnut/SQBeyondPublic#106]
As the title suggests, I started getting shot and as I tried to unpilot the game crashed. The person stopped shooting, and when I logged back on, they started shooting again, and I immediately crashed again. Then a third time I logged in, and this time during some pvp fighting the person was moving their ship around and the third time, I crashed with an unspecified error.
[2019-03-03-4.log.gz](https://github.com/GingerWalnut/SQBeyondPublic/files/2923274/2019-03-03-4.log.gz)
[latest.log](https://github.com/GingerWalnut/SQBeyondPublic/files/2923275/latest.log)
[2019-03-03-3.log.gz](https://github.com/GingerWalnut/SQBeyondPublic/files/2923276/2019-03-03-3.log.gz)

**Comment by GingerWalnut** [comment]
This should be fixed.
