### ISSUE TITLE
Sitting Glitch

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#11]
So when you sit down you can't get back up no matter how much you crouch.

**Comment by daredevil28** [comment]
While piloting a ship? Because I could sit and get back up fine on a normal stair block

**Comment by Jarkyc** [comment]
> While piloting a ship? Because I could sit and get back up fine on a normal stair block

I may have been, I don't remember. It was on slabs. Me and 303 i think it was were having the problem.

**Comment by GingerWalnut** [comment]
Fixed
