### ISSUE TITLE
Ranger Shield Issue

### ISSUE THREAD

**Issue by DemrosO** [GingerWalnut/SQBeyondPublic#112]
I had left the server after unpiloting my ship at Yisheng Hydroponics/Vapid Engineering around 7pm est and came back an hour or so later. I flew to Izifo and went to go check my chests, lots of stuff had been stolen even though my ship had been entirely locked up. Not sure if the WG of the NPCs counteracted my Ranger Shield but it is a problem

**Comment by GingerWalnut** [comment]
Fixed
