### ISSUE TITLE
water on ship after being submarine

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#114]
![image](https://user-images.githubusercontent.com/34897864/53711151-5ea35880-3e06-11e9-9929-abc162bd0447.png)
differerent than water & ships by double because no ladder

this is story

ok sea
story is i was being chased by xlordherobrinex and goldieh
i logged out because i had ship shield, goldieh flew away, xlord logged out on my location.
i logged back on when they were both gone and i started flying. after this xlord starts bitching about how i took his ship. unknowing to me it was stuck to the roof of my ship. so naturally i unpilot, remove the blocks that are sticking them together, redetect, and fly off. except that didn't work. his ship was still stuck to mine even though i kept redetecting and there was AIR between the ships. in the end i just demolished his entire ship because it was stuck following m

**Comment by GingerWalnut** [comment]
Any new instances of this happening?
