### ISSUE TITLE
Water not flowing properly

### ISSUE THREAD

**Issue by JC3371** [GingerWalnut/SQBeyondPublic#116]
![2019-03-03_20 59 52](https://user-images.githubusercontent.com/19299597/53714703-3f0b3080-3e04-11e9-8b0f-707b2653a0b9.png)

Sometimes wheat blocks water, but I think it is an issue with water flowing over tilled dirt.

**Comment by GingerWalnut** [comment]
Does this still occur?

**Comment by JC3371** [comment]
I'm not sure, we redesigned our farms to get around this issue. Haven't seen this issue have an effect anywhere else.

**Comment by GingerWalnut** [comment]
I haven't seen any issues relating to this recently.
