### ISSUE TITLE
Radar Dot Dupe

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#12]
Don't really know whats happening, its just theres a floating green dot next to the radar.

https://imgur.com/a/H6o5tVg

**Comment by GingerWalnut** [comment]
Has this happened to anyone else?

**Comment by Jarkyc** [comment]
> Has this happened to anyone else?

not that i know of

**Comment by Jarkyc** [comment]
never found this again. Just gonna close this.

**Comment by KelvinCrank22** [comment]
I've encountered this pretty much every time I fly my ship nowadays
