### ISSUE TITLE
Shielded ship not allowing access

### ISSUE THREAD

**Issue by awangatboo** [GingerWalnut/SQBeyondPublic#122]
3/5/2019 

I have a shielded ship.  I have been able to change things on it and it works great.  Flew to another planet in a different system and then back home.  Once back at my base I can not interact with the ship.  It is almost as if I am not listed on the region that is my ship.   I cannot look in the droppers, open the docking bay door or change the ship in any way.  The only workaround I have found is to have a junk ship with a shield to start when I need to modify my ship or look in the dropper.  

The reason I mention the data is this was not the case yesterday.

**Comment by GingerWalnut** [comment]
This should be fixed.
