### ISSUE TITLE
Suggestion: Jammers slow shift flying

### ISSUE THREAD

**Issue by LivesParkkk** [GingerWalnut/SQBeyondPublic#124]
It is easy to knock someone out of slipspace or autopilot with a jammer, but space combat is still nearly impossible with the speed both ships are able to shift fly at. Jammer should slow the shift flying speed of all ships affectedb y the jammer (this includes the ship doing the jamming). Even if it is just slowed by a bit, it would make combat much more viable, while allowing ships to get away if they are good enough pilots.

**Comment by Crimsonknight3** [comment]
This isn't a good suggestion. Different ships have different shift speeds already, forcing pirates to have smaller faster vessels seems good for balance to me, meaning pirates cant have massive ships and still attack smaller ones

**Comment by LivesParkkk** [comment]
Current balancing done to make then cheaper is good, I'll have to see how
it works, but you misunderstood my point. The point is that shift flight is
far too fast across the board when it dlcines to PvP, pirate too fast to
hit prey, prey too fast to get hit.

**Comment by GingerWalnut** [comment]
Shift Flying + Jammers have been rebalanced
