### ISSUE TITLE
piloting at stations seems to be forcing redetects

### ISSUE THREAD

**Issue by TiatLief** [GingerWalnut/SQBeyondPublic#125]
this doesn't happen anywhere else, but if at a station piloting your ship seems to cause a redetect and attaches you to things like ships that are being carried or the station itself

**Comment by GingerWalnut** [comment]
Does this still happen?

**Comment by TiatLief** [comment]
I'm not sure, I haven't been to any stations in a while. You may close it for now if you wish and I can reopen it later if the bug reappears.
