### ISSUE TITLE
Someone fired a cannon and i crashed.

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#13]
was looking around, cannons fired, and i crashed. don't know if this is useful

"The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot get property bme{name=facing, clazz=class eq, values=[north, south, west, east]} as it does not exist in Block{minecraft:dispenser}"

**Comment by Jarkyc** [comment]
I only submitted this because this is the second time that this has happened

**Comment by Jarkyc** [comment]
I was watching someones ship move and it happened again.

"Error: java.lang.IllegalArgumentException: Cannot get property bme{name=facing, clazz=class eq, values=[north, south, west, east]} as it does not exist in Block{minecraft:dispenser}"

**Comment by GingerWalnut** [comment]
Has this happened to anyone else or again?

**Comment by Jarkyc** [comment]
> Has this happened to anyone else or again?

no it hasnt, but the people i was with didnt have the texture pack so i assumed it was the pack and turned it off and it stopped happening. turned it on, will tell if it happens again

**Comment by Jarkyc** [comment]
> Has this happened to anyone else or again?

Just happened agin now that i have the texture pack on.:

"The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot get property bme{name=facing, clazz=class eq, values=[north, south, west, east]} as it does not exist in Block{minecraft:hopper}"

**Comment by GingerWalnut** [comment]
This might be fixed at the next restart.
