### ISSUE TITLE
void station not saving data possibly? & not respawning on piloted ship

### ISSUE THREAD

**Issue by Crimsonknight3** [GingerWalnut/SQBeyondPublic#130]
Entering void station on a ship works correctly however upon leaving you are spawned on the spawn station, and returning to the void afterwards results in a missing ship (also the single piece of bedrock that spawns on first entering is also gone)

**Comment by GingerWalnut** [comment]
This was likely a result of the void chunk glitches. To leave the void with a ship, type the exit command while piloting the ship.
