### ISSUE TITLE
Chair pluggin Compatibility issue

### ISSUE THREAD

**Issue by MFBeetus** [GingerWalnut/SQBeyondPublic#132]
If you sit on any kind of chair (slab or carpet) while a ship is moving or starts to move, you will not move with it and it will continue moving while you fall to the ground.
Even after being teleported off of the chair, you will continue to sit like you are in a chair and be unable to move until you crouch.
If you stand up from the chair (Crouch off of it) after you have fallen off the ship, you will be teleported back up to where the chair used to be before the ship moved and you will fall again..

**Comment by Crimsonknight3** [comment]
I can second this. I just ALMOST died in the void by getting into a chair accidently while the ship was moving. Luckily if you are falling and shift or space don't work, if you type /ship exit quick enough, space physics return to normal and you can fly back to your ship

**Comment by GingerWalnut** [comment]
Fixed for next restart
