### ISSUE TITLE
Crashing While on Ship

### ISSUE THREAD

**Issue by DoubleBrackets** [GingerWalnut/SQBeyondPublic#134]
Crash report for a bug that occurs when in a ship. Happens sometimes when shift flying.

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 3/8/19 8:44 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property bme{name=facing, clazz=class eq, values=[north, south, west, east]} as it does not exist in Block{minecraft:dropper}
	at bla.c(SourceFile:95)
	at cwh.a(TileEntitySignRenderer.java:50)
	at cwh.a(TileEntitySignRenderer.java:24)
	at cwa.a(TileEntityRendererDispatcher.java:205)
	at cwa.a(TileEntityRendererDispatcher.java:156)
	at cue.a(RenderGlobal.java:1081)
	at cty.b(EntityRenderer.java:1395)
	at cty.a(EntityRenderer.java:1217)
	at cty.a(EntityRenderer.java:979)
	at cft.c(SourceFile:850)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bla.c(SourceFile:95)
	at cwh.a(TileEntitySignRenderer.java:50)
	at cwh.a(TileEntitySignRenderer.java:24)

-- Block Entity Details --
Details:
	Name: minecraft:sign // bkc
	Block: Block{minecraft:dropper}[facing=west,triggered=false]
	Block location: World: (-1510,90,1169), Chunk: (at 10,5,1 in -95,73; contains blocks -1520,0,1168 to -1505,255,1183), Region: (-3,2; contains chunks -96,64 to -65,95, blocks -1536,0,1024 to -1025,255,1535)
	Block: Block{minecraft:dropper}[facing=west,triggered=false]
	Block location: World: (-1510,90,1169), Chunk: (at 10,5,1 in -95,73; contains blocks -1520,0,1168 to -1505,255,1183), Region: (-3,2; contains chunks -96,64 to -65,95, blocks -1536,0,1024 to -1025,255,1535)
Stacktrace:
	at cwa.a(TileEntityRendererDispatcher.java:205)
	at cwa.a(TileEntityRendererDispatcher.java:156)
	at cue.a(RenderGlobal.java:1081)
	at cty.b(EntityRenderer.java:1395)
	at cty.a(EntityRenderer.java:1217)

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [ctj['DoubleBrackets'/15976581, l='MpServer', x=-1509.50, y=92.00, z=1169.50], ctk['Pr1ckl3s'/15192450, l='MpServer', x=-1510.68, y=90.00, z=1175.96], ctk['JC3371'/15981032, l='MpServer', x=-1510.65, y=90.00, z=1170.67]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,128,0), Chunk: (at 0,8,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 119638 game time, 2039638 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 13 total; [ctj['DoubleBrackets'/15976581, l='MpServer', x=-1509.50, y=92.00, z=1169.50], ctk['Pr1ckl3s'/15192450, l='MpServer', x=-1510.68, y=90.00, z=1175.96], aki['Squid'/15974641, l='MpServer', x=-1537.40, y=64.00, z=1204.60], aki['Squid'/15974640, l='MpServer', x=-1537.40, y=64.00, z=1204.60], amt['Creeper'/15977835, l='MpServer', x=-1507.57, y=65.00, z=1218.18], ctk['JC3371'/15981032, l='MpServer', x=-1510.65, y=90.00, z=1170.67], ctk['JC3371'/15981032, l='MpServer', x=-1510.65, y=90.00, z=1170.67], amt['Creeper'/15975228, l='MpServer', x=-1512.36, y=64.00, z=1210.53], anq['Spider'/15975203, l='MpServer', x=-1520.38, y=62.53, z=1204.11], ctk['Pr1ckl3s'/15192450, l='MpServer', x=-1510.68, y=90.00, z=1175.96], aki['Squid'/15974663, l='MpServer', x=-1559.40, y=97.00, z=1233.60], aki['Squid'/15974662, l='MpServer', x=-1560.22, y=97.00, z=1233.60], aki['Squid'/15974664, l='MpServer', x=-1559.51, y=97.00, z=1232.43]]
	Retry entities: 0 total; []
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crg.a(WorldClient.java:576)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:403)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 878945960 bytes (838 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-OptiFine_HD_U_E6
	LWJGL: 3.1.6 build 14
	OpenGL: Intel(R) HD Graphics 620 GL version 4.4.0 - Build 21.20.16.4534, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/SQBeyond.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.13.2_HD_U_E6
	OptiFine Build: 20190214-140229
	Render Distance Chunks: 10
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4534
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by JC3371** [comment]
These crashes happened a lot today when two groups were fighting. It resulted in a lot of crashing mid fight and as combat dummies were implemented, players who crashed lost their stuff.

**Comment by GingerWalnut** [comment]
This has been fixed in 1.14
