### ISSUE TITLE
Beam transport bugged particles

### ISSUE THREAD

**Issue by Griffinwizard** [GingerWalnut/SQBeyondPublic#136]
The particles from a beam transporter are stuck, moving the ship the transporter was on did not remove them. Not sure what caused it.
![2019-03-09_07 20 22](https://user-images.githubusercontent.com/47922457/54073457-28b60800-423c-11e9-9a1f-4384d61d1711.png)

**Comment by GingerWalnut** [comment]
Fixed with new BeamTransporter plugin
