### ISSUE TITLE
Armor Indestructible?

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#14]
I was laying into some quarts stairs and slabs and it wasn't destroying. 

https://youtu.be/RhbdJLnYyr4

**Comment by GingerWalnut** [comment]
Note to self: rebuff cannons and buff hull hp?

**Comment by Jarkyc** [comment]
> Note to self: rebuff cannons and buff hull hp?

noooo cannons are op enough. is it possible to just debuff armor or is it literally the lowest it can go

**Comment by GingerWalnut** [comment]
I've re-balanced cannons and stuff. Expect at the next restart.
