### ISSUE TITLE
Suggestion: Linked Turrets, and Hangar Doors Back in SQ 

### ISSUE THREAD

**Issue by StarWarden** [GingerWalnut/SQBeyondPublic#143]
So I know we've had hangar doors in past versions of SQ. I really liked the multi-directional hangar doors that Dib coded back in 3.0 or 4.0. I never got the chance to use them but I would like to. The hangar shields are great for sure, but it would be nice to have something that can protect a base from unwanted ships from being flown into the hangar as well. 

Also, I'm not sure what the weapons doctrine is of SQ Beyond compared to previous versions , but it seems that turrets are still meant to be light weapons compared to cannons and heavier things like laser cannons (super cool btw). I agree fully with turrets being the light weapons. I remember back in 2.0 I took one direct hit from a cannon turret; it killed me instantly and blew the entire cockpit off of my gunship. So yeah light is the way to go for turrets. But I really liked the ability to use the linked turrets. Having the master turret that directs the fire of all of the other linked ones is super useful for single pilot ships like I tend to make. If that is too OP though for smaller ships at least I think they should be added to some of the larger ships classes for sure. A battleship that's not very maneuverable to start with is a sitting duck for EMP torps. I remember that was part of the reason linked turrets were implemented in the past  - to make larger ships able to hold their own against smaller fighters and gunships that would typically tear them to shreds otherwise. The heavier weapons aren't super aimable and having a bunch of single turrets on a large ship isn't at all useful unless you have a very large and coordinated crew which is hard to do and not super practical. So if we could see linked turrets back for all classes that would be awesome! Or at least for the larger classes. 

IGN: ThunderStryken

EDIT: Were vertical docking tubes a thing as well? Those would be SUPER useful!

**Comment by GingerWalnut** [comment]
Linked turrets are a thing now. Vertical docking tubes are as well. I don't think we plan on doing hanger doors, but we do have a gate plugin.
