### ISSUE TITLE
Hoppers on ships crashing clients

### ISSUE THREAD

**Issue by TraffyDWL** [GingerWalnut/SQBeyondPublic#146]
I was in a ship fight and got this crash error.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/13/19 6:31 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property bme{name=facing, clazz=class eq, values=[north, south, west, east]} as it does not exist in Block{minecraft:hopper}
	at bla.c(SourceFile:95)
	at cwh.a(SourceFile:37)
	at cwh.a(SourceFile:18)
	at cwa.a(SourceFile:148)
	at cwa.a(SourceFile:128)
	at cue.a(SourceFile:693)
	at cty.b(SourceFile:966)
	at cty.a(SourceFile:875)
	at cty.a(SourceFile:749)
	at cft.c(SourceFile:850)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bla.c(SourceFile:95)
	at cwh.a(SourceFile:37)
	at cwh.a(SourceFile:18)

-- Block Entity Details --
Details:
	Name: minecraft:sign // bkc
	Block: Block{minecraft:hopper}[enabled=true,facing=east]
	Block location: World: (459,76,-2637), Chunk: (at 11,4,3 in 28,-165; contains blocks 448,0,-2640 to 463,255,-2625), Region: (0,-6; contains chunks 0,-192 to 31,-161, blocks 0,0,-3072 to 511,255,-2561)
	Block: Block{minecraft:hopper}[enabled=true,facing=east]
	Block location: World: (459,76,-2637), Chunk: (at 11,4,3 in 28,-165; contains blocks 448,0,-2640 to 463,255,-2625), Region: (0,-6; contains chunks 0,-192 to 31,-161, blocks 0,0,-3072 to 511,255,-2561)
Stacktrace:
	at cwa.a(SourceFile:148)
	at cwa.a(SourceFile:128)
	at cue.a(SourceFile:693)
	at cty.b(SourceFile:966)
	at cty.a(SourceFile:875)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ctj['xLordHerobrinex'/4348891, l='MpServer', x=464.47, y=80.00, z=-2573.66]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,128,0), Chunk: (at 0,8,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 44699 game time, 9068699 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 7 total; [ctj['xLordHerobrinex'/4348891, l='MpServer', x=464.47, y=80.00, z=-2573.66], ctk['Goldieh'/4241679, l='MpServer', x=516.44, y=69.36, z=-2542.70], ctk['KillerMidget'/4159111, l='MpServer', x=453.41, y=76.00, z=-2551.28], ctk['KillerMidget'/4159111, l='MpServer', x=452.46, y=77.00, z=-2525.68], ctk['KillerMidget'/4159111, l='MpServer', x=515.70, y=76.00, z=-2521.37], amm['Dropper'/4350689, l='MpServer', x=496.88, y=62.52, z=-2568.13], ann['Skeleton'/4345612, l='MpServer', x=419.50, y=8.00, z=-2606.50]]
	Retry entities: 0 total; []
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crg.a(SourceFile:418)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:403)
	at net.minecraft.client.main.Main.main(SourceFile:144)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1204014928 bytes (1148 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.24, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/My Pack (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

**Comment by GingerWalnut** [comment]
Fixed in 1.14 MC
