### ISSUE TITLE
Error messages while mining ships after detecting them

### ISSUE THREAD

**Issue by Creepopolous** [GingerWalnut/SQBeyondPublic#148]
If you try to detect a ship, and it fails, the chat will be filled with messages about armor percentages that are too high, or wool percentages when it is too low whenever you mine the ship. The game thinks you are piloting a ship, but since one does not actually exist, you are not kept to the confines of said ship. It will, however, prevent you from piloting another ship until you use /ship exit or log off.

**Comment by GingerWalnut** [comment]
Fixed for next restart
