### ISSUE TITLE
Can't exit turrets

### ISSUE THREAD

**Issue by Pr1ckl3s** [GingerWalnut/SQBeyondPublic#149]
Right clicking with a ship controller while in a turret just makes you look straight up, like it does when you enter a turret. In other words, you can't get out. Also, combat modules show 1/3 for my ship in /ship info even though I redetected with 2 turrets.

**Comment by GingerWalnut** [comment]
Is this still an issue?

**Comment by Pr1ckl3s** [comment]
Nope haven't gotten it for a while
