### ISSUE TITLE
Water & Ships

### ISSUE THREAD

**Issue by DoubleBrackets** [GingerWalnut/SQBeyondPublic#15]
When flying ships through water, water sticks inside ladder blocks. I think this happens when you unpilot and repilot underwater.

![2019-02-22_19 17 30](https://user-images.githubusercontent.com/29745653/53283400-ca950b00-36fa-11e9-9dbd-5fc1db6333fb.png)

**Comment by GingerWalnut** [comment]
This should be fixed
