### ISSUE TITLE
suggestion?: increase capital ship size or give them an additional carrying capacity

### ISSUE THREAD

**Issue by TiatLief** [GingerWalnut/SQBeyondPublic#157]
Cap ships are pretty difficult to build within 10k blocks and have decently sized hangars. Maybe change the block ranges for capital ships to 5k-15k and flagships 15k-25k? Or give both carrying capacities which allow the max block count to increase by up to 1.25-1.5x the parent's ships block count when a ship attaches.

**Comment by Jarkyc** [comment]
Done recently
