### ISSUE TITLE
Texture Pack Suggestions

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#16]
So I have a few suggestions for the texture pack, of course I don't know if it's even finished yet. First glass should connect (connected textures i think it is?). This will make looking out of ship windows better and radars easier to read. Second is please change the leave textures, they look too cartoonish for the pack.

**Comment by GingerWalnut** [comment]
Sent this to the artists

**Comment by GingerWalnut** [comment]
Both of these have been addressed in the new resource pack
