### ISSUE TITLE
Cloak Cooldown

### ISSUE THREAD

**Issue by JUSAPlayer1** [GingerWalnut/SQBeyondPublic#164]
Can we change the cloak code to subtract the remaining time on your cloak from the cooldown timer? Cause atm if I activate cloak, use it for 1 minute, and shut it off, i have to wait 2 minutes then it says it deactivated and then wait another 8 minutes for the cooldown. Not sure if this is intended or not but it seems unnecessarily long and doesn't really allow for people to toggle their cloak as freely as it could.

**Comment by GingerWalnut** [comment]
In the next update, cloaking devices should be toggle able and the cool down length should be proportional to the use time.
