### ISSUE TITLE
Elevators do not work in void station

### ISSUE THREAD

**Issue by Laserlance141** [GingerWalnut/SQBeyondPublic#166]
Title, tested in faction Void Station

**Comment by GingerWalnut** [comment]
Do they work in private void stations?

**Comment by icekoob** [comment]
you can't open trapdoors in faction void stations either

**Comment by HailOVERLORD** [comment]
You can't open ANY type of doors in the void. It makes it difficult to complete building ships.

**Comment by GingerWalnut** [comment]
Fixed for next update
