### ISSUE TITLE
Suggestion: ship spawner colours

### ISSUE THREAD

**Issue by Elttob** [GingerWalnut/SQBeyondPublic#17]
I remember from way back that you could personalise your noob ship at spawn by choosing a colour of wool for the ship, this would be a nice touch for SQB I think :p

**Comment by Elttob** [comment]
How I'd imagine it working: add a third sign on the ship spawner which says the current colour and 'click to choose colour' or something, each time you click it cycles through the different colour options (red, orange, yellow, lime, green, cyan, blue, purple, magenta, pink). Then just replace all red wool with the correct coloured wool when the ship is spawned.

**Comment by GingerWalnut** [comment]
Done
