### ISSUE TITLE
siege is broken

### ISSUE THREAD

**Issue by LivesParkkk** [GingerWalnut/SQBeyondPublic#171]
unable to overclaim (error"this chunk is not involved in a siege") even if the chunk is adjacent to the capital ship. Also if all members log off siege is essentailly stopepd because explosions turn off.

Should also be able to siege without their land being more than their power. You should be able to tp siege at any time but only overclaim if they are overclaimable.

**Comment by GingerWalnut** [comment]
What were you siegeing?

**Comment by LivesParkkk** [comment]
Singing capital ship

**Comment by GingerWalnut** [comment]
Was the capital ship in a claim other than it's own claim?

**Comment by LivesParkkk** [comment]
Don't think so, their main claim was on yavar, the capital ship was on
feldost, sieged the capital ship, /f who said they had 1 capital ship and
no outpost claimed.

**Comment by GingerWalnut** [comment]
Had the siege finished preparing by the time you tried to overclaim it?

**Comment by LivesParkkk** [comment]
Yes,we were about 30 minutes in.

**Comment by GingerWalnut** [comment]
Fixed for next restart
