### ISSUE TITLE
Feldost sky limit isn't high enough

### ISSUE THREAD

**Issue by Skitz12** [GingerWalnut/SQBeyondPublic#175]
The sky limit for Feldost is definitely not high enough, most of the time you spawnon top of a mountain and you are trapped by trees surrounding your ship and the only way to get out is to fly up, however you can't fly up because the sky limit transports you out of the planet.

This needs to be fixed as it is an extremely irritating issue.

Thank you!

**Comment by GingerWalnut** [comment]
This cannot be fixed because minecraft's sky limit cannot be increased and the ships use minecraft's sky limit for when to jump into space. You can try using autopilot to go past the trees or approach the planet from a different angle.
