### ISSUE TITLE
Slipdrive arrows stay

### ISSUE THREAD

**Issue by LivesParkkk** [GingerWalnut/SQBeyondPublic#177]
if your slipdrive is jammed, the arrow remains until next restart.

**Comment by GingerWalnut** [comment]
At what point was the slipdrive jammed?

**Comment by LivesParkkk** [comment]
Slupdrives only get jammed at the very end, there is no indication they're
being jammed until it tries to jump and fails.

**Comment by Jarkyc** [comment]
Fixed a while ago
