### ISSUE TITLE
Suggestion: show current planet in chat instead of [Global]

### ISSUE THREAD

**Issue by Elttob** [GingerWalnut/SQBeyondPublic#18]
[Global] takes up a lot of space and is kinda redundant since most of the time people will talk in global, so for messages in global chat maybe the global tag could be replaced with abbreviated planet names e.g. [Kel] or [Avaq]

**Comment by GingerWalnut** [comment]
I would like this, but it would be difficult with the current chat plugin. I might be able to make it work. Worst case scenario, I eventually write my own chat plugin for those couple of features we want.

**Comment by Jarkyc** [comment]
I will not be doing this due to the fact that it will expose people who are cloaked or on a rouge planet, basically if people want to be secretive, it will just blow their cover.
