### ISSUE TITLE
Suggestion: Credit sinks into ship replicator

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#180]
Make ship replicators have the option to spend credits for general ship blocks like wool, concrete, terracotta, etc. I don't think valuable blocks like diamond/iron blocks should able to replicated, and the price for the blocks allowed to be spent with credits should be pretty high.

Also please make replicators tell you what ur missing

**Comment by GingerWalnut** [comment]
done
