### ISSUE TITLE
Beam transporters must be re-detected after every restart to function

### ISSUE THREAD

**Issue by TiatLief** [GingerWalnut/SQBeyondPublic#182]
This is bad especially when you log off overnight on the ground. Beams also need to be redetected after the ship is moved but that isn't much of a problem and possibly preferable,

**Comment by Jarkyc** [comment]
I tried recreating this in a single player world and couldn't. Can you tell me if this still happens?

**Comment by Seamonster778778778788** [comment]
sure

**Comment by GingerWalnut** [comment]
Fixed with new beam transporter plugin
