### ISSUE TITLE
Beam Transporter glitched (Pic, planet, and coords included)

### ISSUE THREAD

**Issue by Sofetios** [GingerWalnut/SQBeyondPublic#184]
There are two spirals of smoke going into the sky at my claim. I didnt do anything, though someone who was recently here might have done it. I was told its a beam transporter that is glitched. Its on the planet Mardos, Coords: X=-1775 Z=220 Y=72. If the smoke can be taken away, i would really appreciate it. thank you. ~Sofetios
![2019-04-04_15 28 40_2](https://user-images.githubusercontent.com/15205173/55583479-f939d480-56ef-11e9-8fa8-452a68431b4b.png)

**Comment by Jarkyc** [comment]
Smoke goes away after restarts. If possible it would be really helpful to know information that led up to the glitch. If not that’s fine.

**Comment by GingerWalnut** [comment]
Fixed with new beam transporter plugin
