### ISSUE TITLE
Ship owned by a person in a faction still has a shield around it

### ISSUE THREAD

**Issue by fiercedude** [GingerWalnut/SQBeyondPublic#185]
I saw that a ship owned by killermidget had a destroyed ship near my base, so I went to salvage it. When I got there I discovered that even though he was in a faction, the ship had a shield around it and I can't destory any blocks.

![2019-04-05_23 13 09](https://user-images.githubusercontent.com/19196262/55673602-041f7100-5878-11e9-9695-6ced1b71b8c2.png)

**Comment by Jarkyc** [comment]
Not a bug, just the way the system works. System will be reworked to prevent this happening with other ships.
