### ISSUE TITLE
Flight at bottom of space

### ISSUE THREAD

**Issue by HailOVERLORD** [GingerWalnut/SQBeyondPublic#186]
When you are spacewalking too close to the lower limit of space, the flight gets glitchy and you fall and get stuck and constantly get teleported up to keep you from falling into the void.

**Comment by Jarkyc** [comment]
Are you able to tell if it’s the fact that gravity is glitching out or are you being teleported.

**Comment by HailOVERLORD** [comment]
I believe that it was gravity glitching out.

**Comment by Jarkyc** [comment]
Know problem. Working on fix.
