### ISSUE TITLE
Suggestion: Bridge Monitors

### ISSUE THREAD

**Issue by HailOVERLORD** [GingerWalnut/SQBeyondPublic#188]
I (and probably many others) when planning the construction of ships larger that gunship class would like to put the bridge of my ship in a protected area in the center of my ship. The problem with this, however, is that if I am on the bridge and surrounded on all sides by armor, I cannot see outside.  In Star Trek, the Enterprise had a monitor that allowed the command crew to see what was going on outside their craft. I would love to see something like this implemented in Starquest Beyond. Perhaps have a custom recipe for a "camera" block that is armored that you place on the exterior of your hull that faces only in one direction and links to a monitor module on the bridge?

**Comment by HailOVERLORD** [comment]
P.S.
This idea is similar to but slightly different from the ship cameras suggestion.

**Comment by GingerWalnut** [comment]
There isn't a good way to do this that wouldn't cause a lot of lag on the server due to how minecraft works.
