### ISSUE TITLE
two bugs regarding capital ships in the void

### ISSUE THREAD

**Issue by icekoob** [GingerWalnut/SQBeyondPublic#189]
Capital ships are able to make claims in both the faction and personal void station when you unpilot, even though it explicitly says something like "you cannot make claims in the world" when you try to "./f claim" in the void world. Those said claims can also be sieged, and you can find the void coordinates of the capital ship via sieging the ship.

**Comment by GingerWalnut** [comment]
This has been fixed for the next update
