### ISSUE TITLE
Cloaking devices can regularly simply be turned on and off without cooldown, or break completely.

### ISSUE THREAD

**Issue by AdinaThepotato** [GingerWalnut/SQBeyondPublic#191]
To stay cloaked, forever. You can turn the cloaking device on and off fast enough, so that you stay hidden. This doesn't even activate the cooldown. And if it does, the cooldown is nonexistant. 

I have no idea how the cloaking device simply didn't want to shut off, but I do think the fact you can just turn it on and off and stay hidden forever, is quite, broken.

**Comment by GingerWalnut** [comment]
I found a bug with the time remaining code and fixed it. In addition, I made the percentage used of the time have a minimum of 5% so you can't just spam it on and off.
