### ISSUE TITLE
Suggestion: Rule against box ships

### ISSUE THREAD

**Issue by HailOVERLORD** [GingerWalnut/SQBeyondPublic#192]
Pretty self explanatory.  Box ships are ugly and take away from the overall atmosphere of the server.   There should be some kind of rule or discouragement against them.  This may be hard to implement in practice, especially because there are some intentionally good looking box like ship models *cough Tardis* that can be made. Still something that I would like to see something done about.

**Comment by Jarkyc** [comment]
There was a rule for ship look regulation but it was removed recently because there was a lot of controversy over what was a box or not actually a ship, and what was something practical like an escape pod or something.

**Comment by Jarkyc** [comment]
As for whether they’ll add it back in I’m not sure so I guess I’ll just put the suggestion tag?

**Comment by GingerWalnut** [comment]
It would be difficult to implement this in practice. Additionally, some people are just not good at creativity and they may end up being punished by this.
