### ISSUE TITLE
"custom" tree leaves don't despawn

### ISSUE THREAD

**Issue by icekoob** [GingerWalnut/SQBeyondPublic#197]
basically, on feldost the tree leaves don't despawn, and it's very annoying.

**Comment by Jarkyc** [comment]
I haven’t had this issue. Make sure there isn’t wood like surrounded by leaves so you can’t see it.

**Comment by icekoob** [comment]
yeah i’ve made sure about that and they still don’t despawn

**Comment by GingerWalnut** [comment]
This has been fixed, perhaps a little too much.
