### ISSUE TITLE
Message is broken

### ISSUE THREAD

**Issue by LivesParkkk** [GingerWalnut/SQBeyondPublic#2]
https://gyazo.com/dfda83e5297bc726a31c31f0e6ad0a5d

no perms for msgtoggle and when you type in chat it messages them and also shows that.

also petition for the command to be /m for simplicity, and whatever reply is to be /r as well.

Tabbing does not autocomplete the person's name after typing /msg, meaning you need to manuall;y type in their name.

**Comment by GingerWalnut** [comment]
Has message broken for anyone else?

**Comment by GingerWalnut** [comment]
Fixed for next restart
