### ISSUE TITLE
Chunk grew back

### ISSUE THREAD

**Issue by fiercedude** [GingerWalnut/SQBeyondPublic#20]
I cut down trees near my base, and the next day one of the chunks I had cut down had turned back to what it was before.

**Comment by fiercedude** [comment]
![2019-02-23_14 26 01](https://user-images.githubusercontent.com/19196262/53292765-da156200-3795-11e9-97fa-0f1b8c058013.png)

**Comment by GingerWalnut** [comment]
This is more likely than not something to do with dynmap rendering chunks. reopen this (or a new issue) if it happens again.
