### ISSUE TITLE
frozen grallion and asteroid belt

### ISSUE THREAD

**Issue by icekoob** [GingerWalnut/SQBeyondPublic#202]
having frozen grallion(water planet with floating islands) as a moon or a planet would be an awesome addition to starquest due to the lack of “snowy/frozen”. adding an  asteroid belt in the outerrims of the “illegal” systems would be also neat because right now asteroids are a bit underused and re-adding asteroid belts would be nice.

**Comment by Jarkyc** [comment]
There are discoverable asteroid fields

**Comment by GingerWalnut** [comment]
Grallion is rogue and moving asteroid fields are now a thing
