### ISSUE TITLE
Flak launchers behave weirdly in the direction they're facing

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#203]
Depending on which way the flak launcher is facing, it fires different, meaning you can only armor it in certain ways.

When flak launchers face North or West, they can fire like this just fine and the shots don't hit anything on your ship.

![image](https://user-images.githubusercontent.com/34897864/56440150-2ff61a00-62ae-11e9-81b7-4f608115d722.png)

However, if they're facing East or South, half of the shot hits the iron bars below it, while the other half goes above just fine. 

You can also armor the flak launcher like so
![image](https://user-images.githubusercontent.com/34897864/56440242-777ca600-62ae-11e9-9cda-893e3ffe8ccb.png)

OR with a block in front of it like this
![image](https://user-images.githubusercontent.com/34897864/56440308-a5fa8100-62ae-11e9-82b9-028cb30df4c2.png)

And it fires just fine, ONLY if its facing North or West, one of the working directions I said above.

I believe this happens because of the way the snowball entities get spawned and launched based on the orientation of the flak launcher.

This can be remedied by just moving it up one, or not armoring it with iron bars

**Comment by GingerWalnut** [comment]
In the next update, the orientation of the flak launcher shouldn't affect how you can armor it.
