### ISSUE TITLE
Suggestion: A way to tell how long someone has been playing

### ISSUE THREAD

**Issue by SomethingSomethingAllison** [GingerWalnut/SQBeyondPublic#207]
I think it'd be really beneficial to newer players and older players alike to have some command that tells someone how long a specific person has been playing, that way we can stop people from killing and driving new players away. I'm not saying make refs and settlers unkillable for a time, I think that pirates and privateers should beable to see how long someones been playing though.

**Comment by fin444** [comment]
`/res <player>` shows the first log-on date of a player, as well as their wallet and town (among other things). This makes it relatively easy to tell how experienced and powerful a player is.
