### ISSUE TITLE
not being to hit someone 100% of the time

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#208]
you seem to only hit people 1/4th of the time then hit them a few times then go back to not hitting them, i only tested in space

update: all arrow projectiles and everything

**Comment by Jarkyc** [comment]
I've noticed this happens when someone is on a ship I think

**Comment by Seamonster778778778788** [comment]
@Jarkyc high priority pls

**Comment by GingerWalnut** [comment]
Probably fixed for next restart
