### ISSUE TITLE
Not being able to interact with drone ship sign after redetecting another ship

### ISSUE THREAD

**Issue by JC3371** [GingerWalnut/SQBeyondPublic#211]
After redetecting a ship I was working on, I was unable to pilot my drone and it gave this message: You cannot interact with a ship sign of another ship! 

Not sure if this a problem with anything else besides a drone. 

Fixes by relogging. 

Note: After relogging to fix the issue I get teleported back to the ship which I redetected

![2019-04-21_14 53 54](https://user-images.githubusercontent.com/19299597/56476023-9cefe800-6445-11e9-8c03-6beb9f8b0e4c.png)

**Comment by GingerWalnut** [comment]
I think this has been fixed. Let me know if this happens again
