### ISSUE TITLE
Jane Suggestion: Add planet resources to her responses

### ISSUE THREAD

**Issue by JC3371** [GingerWalnut/SQBeyondPublic#219]
For example if someone says "Jane iron planets" Jane will list out the planets that have iron and the resource abundance each planet has. Could also apply to wool and stuff.

**Comment by Jarkyc** [comment]
We have a wiki

**Comment by JC3371** [comment]
New players may not look at the wiki and we lose players cause there is a big learning curve. I think it would be fairly easy to implement this and it will be helpful to new players in game
