### ISSUE TITLE
nerf klon

### ISSUE THREAD

**Issue by icekoob** [GingerWalnut/SQBeyondPublic#220]
maybe make it 1k per anomaly instead of 2k?

**Comment by Seamonster778778778788** [comment]
this man's has the audacity to grind klon for 6 years then say nerf it smh

**Comment by icekoob** [comment]
it literally requires no effort or maybe i’m like way too high level for it

**Comment by icekoob** [comment]
either way buff skywatch too

**Comment by icekoob** [comment]
dont massively nerf it like how digitalia and syndicate did tho

**Comment by Seamonster778778778788** [comment]
@GingerWalnut nerf klon this boy has 4mil klon rep

**Comment by Jarkyc** [comment]
#ResetKoobsKlonRep2019

**Comment by icekoob** [comment]
CHANGE IT TO 1K PER ANOMALY AND MAYBE IM JUST GOOD AT STARQUESTING AS A COLONIST

**Comment by GingerWalnut** [comment]
Klon is going to be nerfed (although not in this way) in the next update
