### ISSUE TITLE
SQTech crafting tables can't craft concrete powder

### ISSUE THREAD

**Issue by Pr1ckl3s** [GingerWalnut/SQBeyondPublic#222]
I tried with other recipes, like iron bars and colored wool, but they just don't seem to work with concrete powder (of any color).

**Comment by Seamonster778778778788** [comment]
Try it with stained glass or recoloring wool? @pr1ckl3s

**Comment by Pr1ckl3s** [comment]
Stained glass works... maybe it's because there's 3 different types of items in the concrete powder crafting recipe?

**Comment by Jarkyc** [comment]
Have noticed this with concrete too.

**Comment by GingerWalnut** [comment]
Fixed for next restart
