### ISSUE TITLE
the flying speed in void is pretty slow

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#228]
its your own personal area and you fly at the speed of space... shouldnt it be higher?

**Comment by Jarkyc** [comment]
I don’t believe there’s anything in the code separating void speed from space speed. I’ll take a look but you might be going insane.

**Comment by Seamonster778778778788** [comment]
it's a suggestion to make flying in void go faster.

**Comment by Seamonster778778778788** [comment]
it a suggestion dumbie

**Comment by Jarkyc** [comment]
Let me live

**Comment by GingerWalnut** [comment]
Implemented for next update
