### ISSUE TITLE
Combat Dummy Bug?

### ISSUE THREAD

**Issue by BoyWonderFTW** [GingerWalnut/SQBeyondPublic#232]
So I was building a capital ship on Mardos late last night (5-5-19) and I took a shuttle down to the floor of my hangar and logged off for the night (around 9-10pm PST). There were no hostile mobs in sight and the area was well lit. There were also very few players online at that hour. Once I logged back on today at around 4pm PST, I got a greeting saying I had died with all my items and 28 levels because my combat dummy was slain, despite being nowhere near combat. Im not sure if this is a bug or my own fault? Help would be appreciated. If needed I can explain further in game. (IGN: BoyWonderFTW and base referred to is on Mardos under Isolators faction)

**Comment by GingerWalnut** [comment]
I've fixed some of the bugs with combat dummies
