### ISSUE TITLE
ship spawner

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#234]
sometimes ship spawners get clogged halfway because of someone partially flying out and leaving it there, and clear button doesnt clear all of 

my idea is

- make clear ship spawner button fix the glass door, and clear the entire ship spawner room
- make it include an area in front of the ship spawner so people can actually fly out incase someone is blocking it still

**Comment by GingerWalnut** [comment]
This has been done
