### ISSUE TITLE
Abuse

### ISSUE THREAD

**Issue by OldDewd** [GingerWalnut/SQBeyondPublic#235]
While it's not a bug, I disagree with the 24 hour ban on me for rage quitting after everyone started mistreating me for trying to avoid discussing it in the first place.. I implore you .. go back and look at fac, global and private messages from that time frame and see for yourself if I didn't tell him at least TWICE not to get Sea involved. I knew it would go nowhere and I was just looking for a sympathetic ear from the people who were supposed to be on my side. Instead he took that, which was already annoyingly out of control and brought it to the global channel so it could blow up and become a bigger problem.  No one believes me.. I'm some crazy old man who should be doing something else besides playing a video game... perhaps I'll shine up my .45 and use it on my skull because every time I get into a server and start having fun, the children take it all away from me anyway and tell me there's something wrong with me if I'm 50 (and handicapped and kind of mentally retarded from a stroke) and I'm playing kids games..  I'm doing that because they USED to give me pleasure.. When I got tired of having fun playing by myself, I ventured out into public servers.  The problem is.. every time I get into a server and start playing as hard as everyone else, all the kids start complaining and pushing my trigger buttons and making everything look like it's my fault... and muting me in faction discord chat wasn't enough.. he went ahead and kicked me from the fac and separated me from all the work I've been doing for it, and all of the stuff that's rightfully mine..  Of course, I should have expected this from the faction that insides and I don't really care that much because we assumed that unclaimed base, but I've made improvements and provided him with easily a million in resources that he sells here and there.  Why would you so readily be wiling to lose your most valuable asset unless you're not really part of the team to begin with?  I'm sorry I cursed and quit.. I know that's against the rules and since I've NEVER knowingly, intentionally or accidentally broken that rule, I think a  3 hour ban is more appropriate.  Just my thoughts on the matter.. I like you, Ginger.. I like your server.  I like how you've set it up.. I like the systems and the fact the planets move like a real solar system.. flying the ships is fun, even if it's laggy.. combat is next to impossible, especially with bigger ships and all the lag so I thought it was real suspicious that he was so far away and without any sign of slipping, it appeared as if he was in cloak.. the fact that he came out of cloak/slip directly in front of me at y 24, with his weapons perfectly placed for a guaranteed strafe on me was a little too much coincidence and that's all I ever have had to say on the matter.  No one flames Molly for crying for TWO WEEKS now about some OTHER faction getting insided by someone trying to join Jusa's fac since he got to the server, truth be told.  There was a price for getting into Novaria, and we all know what that is.. It was my ONE transgression I swore I'd never make again, yet she's still crying about it and no one's asking for mute for her and if they did, they'd probably get kicked for it.. The server is very unbalanced right now and the plebs (pacifists that want a totally peaceful server where no one steals from anyone and there's full time safe space flight) have too much say with their complaining to the point where it seems like pirates are no longer going to be able to pirate... how does that work?  I've seen your direct messages on how we HAVE to keep it a PVP server.. PVP above all else, because peaceful is boring and people will leave.. well, now that there's word that priating will come with penalties by admin and other potential changes, people have ALREADY left and are vowing to not return.  Nexeon won't play, Seahat's gone since I insided them (which I really feel bad about, IRL because they were nice to me) and actually the whole of oblivion hasn't been on in days if not weeks... it's falling apart and you want to ban for 24 hours the ONE GUY that spends at least 10 hours PER DAY in your server, trying to be online for other people to have a target or at least to hopefully get them to join.  I have no ill intentions here, but I will not sit here and be called names and abused because I'm a handicapped housebound PTSD victim.. I just won't.  No denying me of my constitutional inalienable rights on a server run within the country where those rights are upheld will succeed.  Private or no, you can't infringe upon people's god given human right to speech and air grievances.  You can ask nicely for a report to be made with promise to look into said report, but without that having been done, and people telling me admin won't care anyway because there's no questioning of the dictator-style rules we have what's the point of even reporting it?  You're just going to say 'he's not cheating.. even if he is, because MORE people will leave the server and never return if they find out admins have players and they're helping themselves succeed where it would be damn near impossible for them to.. He's NEVER been able to catch me before, so how was it so easy this time?  That's all I'm musing.. I'm not even looking for an answer, i"m just expressing disbelief.  Can't I do that?  Three separate occasions, I saw something I couldn't explain.. the most confusing of which was when he raided the base.. I know he can blow up blocks and they regenerate after the raid, but I was down over FIFTY BLOCKS, inside a double-layered brick bunker and when the side of it disappeared and light from an irregular vertical shaft showed him sitting in some craft, half in and half out of the stone before he fired the fatal shot from his TWO CANNONS on front.. no torp... I was like HOW THE HELL?!  I heard no explosions, couldn't hear him coming down, like I though I could or I would have run deeper into more layers of protection before he got to my level.. I was looking up there and nothing.. no name tag, no explosions, no bombs going off, just blip, open, blip dead.  like it was nothing.
anyway, unban me in 3 hours if you want, unban me tomorrow... because of bonzer kicking me from the fac, there's no real reason for me to come back at all anymore. and that's a loss of a 10 plus hour per day player... every day.. including weekends.  Wouldn't you rather have someone who comes in, works hard, doesn't say much unless something weird happens and plays for half the day every day than someone who comes on, takes advantage of everyone, steals all that person's work without so much as a 'I'm taking this to sell.. I'll give you your share when I get there'... i mean... dude... Why would ANYONE want to play like that?

**Comment by OldDewd** [comment]
I mean, I've been in here for 2 months and you've heard 2 outbursts from me before today yet everyone's willing to hate on me for questioning how stuff happened to me that I was easily escaping before.  Yet everyone still hates me... and you all say it has nothing to do with age, yet everyone brings it up while they're flaming me so I'm failing to see the connection.

**Comment by OldDewd** [comment]
Maybe it's because I"m honest to a fault.. wear my heart on my sleeve, say what I'm thinking/feeling when the mood strikes me.. I'm not really sure, but whenever I try to express myself, I usually just wind up getting stuffed in a box and put on a shelf.. it's just... not worth it anymore.

**Comment by OldDewd** [comment]
Nobody deserves a life like mine.. I hope none of you can ever relate to what I'm going through in your lifetime.  I know why suicide is so common in men with my condition.  It's a hopeless life.  You can't make friends and you can't keep the ones you do because everyone turns their back on you because you're weird, eventually.

**Comment by OldDewd** [comment]
Probably not a good thing to share, because it's painfully honest and you guys hate that.. but you all made a grown man cry today and contemplate suicide... again... I hope you all fee accomplished.
I've shed literal tears over this nonsense and gross mistreatment of the entire situation... and I feel slighted, insulted and taken advantage of... again.

**Comment by OldDewd** [comment]
For your information, people like me since 1995 have created this world you all are playing in.  It's really ironic that you're all actively trying to prevent us from having a part in it.. .like we made it for you or something... kind of like the work I was doing for the Faction and bonzer took all for himself... We made all this because it was for US.. the original gamers.. not some kids to come and try and boot us from.

**Comment by OldDewd** [comment]
anyway, no one's listening, no one cares, I'm just digging deeper, so enjoy your 3 player base.. hope that works out for you.  lol.. wow.  just wow.

**Comment by Seamonster778778778788** [comment]
![image](https://user-images.githubusercontent.com/34897864/57488939-2b53ce80-727a-11e9-8141-432ef0f65432.png)
i had a torp on it to be fair

**Comment by OldDewd** [comment]
Neat.. now explain why all the graphics are fucked up? how do you see outside and inside at the same time and how did that ship get down there and how did you one shot the box?  I guess that's all I really wanted a believable explanation on in the first place.
because, if you can just silently slice through 50 layers of dirt and rock and one shot a two layer thick stone brick bunker, there's really no sense in my playing anymore.. I can't play in stuff that doesn't make any sense at all.

**Comment by OldDewd** [comment]
do bombs and other things not make any sound during a raid?  that would be pretty stupid

**Comment by OldDewd** [comment]
what is that?  a speeder? how many modules do you get on those?

**Comment by Seamonster778778778788** [comment]
@OldDewd ./gamemode spectator
the boxes are chunks you can enable with f3 + g
i shifted

**Comment by Seamonster778778778788** [comment]
its a speeder

**Comment by Seamonster778778778788** [comment]
plus you unshifted while typing at one point and i remembered the location

**Comment by OldDewd** [comment]
Ok, so you have the modules.. was it lined with bombs or drills or something?  How did you get that deep, silently, while I was lookin up for you?
and how come I couldn't see you until you blew open the box?

**Comment by OldDewd** [comment]
I mean certainly I should have heard your speeder or whatever you were using to get rid of enough blocks to fly it down there, or there's another reason to stop playing...

**Comment by OldDewd** [comment]
if people can silently drill through 25 layers of dirt and 25 layers of stone what's the point of even having a base?

**Comment by Seamonster778778778788** [comment]
I dug down... there is still a cobble and prismarine pillar (prismarine which i stole from you earlier)
idk why you couldnt hear it
I placed it down there with wool blocks, I had 25 because thats the min for speeder
I took the signs sponge and dispenser after blowing you up. also that chunk is unclaimed.

**Comment by OldDewd** [comment]
what's the point of claims.. what's the point of any of it?

**Comment by Seamonster778778778788** [comment]
![image](https://user-images.githubusercontent.com/34897864/57489326-496dfe80-727b-11e9-85da-6ef394757240.png)

**Comment by OldDewd** [comment]
not where I was

**Comment by OldDewd** [comment]
I was inside the claim in a double thick stone brick box.. I knew I was close to the edge, but I figured I'd hear you coming and just run deeper into the base, which was an option for me.
you totally freaked me out when you just appeared in a hole without a sound.. that's what I'm freaking out about.

**Comment by Seamonster778778778788** [comment]
you were just inside the claim.. which I blew up because raid turns on explosions.. which can be turned on on level 3 + facs, which yours is

**Comment by OldDewd** [comment]
right... and you HEEAAARRRRR those explosions, right?

**Comment by Seamonster778778778788** [comment]
i only blew it up once... because I mined it out and then placed the speeder blocks and then fired the torpedo

**Comment by OldDewd** [comment]
i heard nothing but silence.. the only sound I heard was 'pachow' when you fired your cannon at me and killed me.

**Comment by Seamonster778778778788** [comment]
it was a single explosion cuz u were close to the edge

**Comment by Seamonster778778778788** [comment]
i will show you the hole you were in

**Comment by OldDewd** [comment]
there's no way you could have done that and not shown your nametag at some point.

**Comment by Seamonster778778778788** [comment]
i was shifting?
and you were shifting looking away when i blew it up

**Comment by Seamonster778778778788** [comment]
![image](https://user-images.githubusercontent.com/34897864/57489449-b1bce000-727b-11e9-9bb2-4387d308812a.png)

**Comment by OldDewd** [comment]
I was sitting there, STARING AT WHERE YOUR ICON SHOULD BE, looking for a nametag.. I didn't see one until you blew a hole in the wall with your speeder.  so something glitched and I was not able to hear you digging down or anything.  Or like I said, I would have juist gone deper.

**Comment by OldDewd** [comment]
sure looks like xray lite to me...

**Comment by Seamonster778778778788** [comment]
how do you know what that looks like?

**Comment by Seamonster778778778788** [comment]
go into single player creative and do ./gamemode creative :P

**Comment by OldDewd** [comment]
because I've been a mod on other servers before.

**Comment by OldDewd** [comment]
and caught people cheating.

**Comment by Seamonster778778778788** [comment]
https://www.digminecraft.com/game_commands/gamemode_spectator.php

**Comment by OldDewd** [comment]
I'm giving you the benefit of the doubt here and telling you that there was a LARGE lag spike or a glitch that prevented me from hearing you come down.. you were only like 8 blocks away when you opened my bunker.  I would have heard the dirt and stone breaking.

**Comment by OldDewd** [comment]
and ran deeper into the base .. maybe you'd have still got me, but not so easily.

**Comment by OldDewd** [comment]
So, what you're saying is you did all that and then used mod powers to go creative and fly around and take a bunch of screenshots?   wtf dude?

**Comment by Jarkyc** [comment]
I'm going to pop in here and please say don't start a flamewar on the github. If you have a problem a feel like posting it here that is fine, I can bring it up to ginger and see if he feels it is right to post it here and we will eventually deal with it. But starting a 50 thread post doesn't solve anything, so please stop.

**Comment by Seamonster778778778788** [comment]
well i'm sorry? i didnt do anything wrong
I understand you're upset but theres no need to play the victim card. you can appeal to oldskool on discord
this isnt the place to talk about it and you should probably calm down a bit. this is a minecraft server as well, not the united states government as they dont have jurisdiction over a minecraft server..
as jark said, either go into my private messages or leave for a bit and cool off

**Comment by OldDewd** [comment]
please don't call it a flamewar, we're actually talking about it with hopes of resolution.

**Comment by Seamonster778778778788** [comment]
Sea#8709

**Comment by OldDewd** [comment]
I'm not upset.. about that... i'm upset because you all are blowing it out of proportion when, for the last time, I TOLD BONZER NOT TO MAKE IT A PUBLIC THING.  I told him I didn't want to TALK ABOUT IT publicly.. I was just venting.

**Comment by Seamonster778778778788** [comment]
okay man, thats you and bonzer to deal with.. not us

**Comment by Seamonster778778778788** [comment]
this is the place for bugs not ranting :p

**Comment by OldDewd** [comment]
I'm upset because I SAID, it was really weird how all this happened.. plain and simple, and he goes and drags it out, gets me talking and then makes it public.. where in public I said I didn't want to talk abou it either but here we are, everyone drug it out into the open and I'm suffering for it.. THAT is why I will probably not be back.. for a long time.. if ever.... unless some unbans happen and some fac membership is reinstated, and servers on discord are rejoined and I get to make a public apology for a private discussion with my faction mate (who I thought I could speak candidly to) that I was FORCED into after REPEATEDLY saying I knew where it was going to to and didn't want to go there.
hence the statement about failing the screwingoveroldpeople test.

**Comment by Jarkyc** [comment]
Please stop before I lock the thread

**Comment by OldDewd** [comment]
How much more adult-like and diplomatic could I have been about it.

**Comment by OldDewd** [comment]
I'll do it for you.

**Comment by Seamonster778778778788** [comment]
@Jarkyc lock the thread
Olddude, PM me about it

**Comment by OldDewd** [comment]
Jarky I'm off all the servers.. I left them all in disgust after people just muted me instead of helping me to understand what happened... so I can't dm you.
