### ISSUE TITLE
Out of contact

### ISSUE THREAD

**Issue by OldDewd** [GingerWalnut/SQBeyondPublic#236]
Jarky I can't DM you because I quit all the discord servers in disgust when everyone wanted to flame me instead of try to help me understand, more than "because I said so'.

**Comment by OldDewd** [comment]
I'm on a 24 hour ban for first offense swearing... I mean.. I"m just feeling overly abused for something I tried to prevent from happening in the first place.

**Comment by OldDewd** [comment]
Will you guys PLEASE stop deleting my comments and TALK to me?
I have no way to DM anyone anymore.

**Comment by Seamonster778778778788** [comment]
@OldDewd PM me. My discord is Sea#8709
Add me through discord with that. I will give you anyones contact info

**Comment by Seamonster778778778788** [comment]
https://discordapp.com/invite/0tUluUyNrchydOIb

**Comment by OldDewd** [comment]
sent a friend request because we don't share any servers any longer.

**Comment by OldDewd** [comment]
So no chance of a successful unban request on this first offense cuss/quit?

**Comment by OldDewd** [comment]
YOu do realize that if you do, unflexingly and without any kind of mercy intend to hold me to a full 24 hours of ban, you will lose me.  I don't play for dictators.  I offered to make a public apology and it's my first offense... If you make me wait 24 hours, I will be over you in 6 and you'll never see me again.  Just sayin'

**Comment by OldDewd** [comment]
you have two to decide.  Ask JC what I have to bring to the table to the first MC server that qualifies for it... ever wish you could pay someone to mod or develop, or get paid for your work?  Alienate the one guy with money and a willingness to support a server financially, IN TOTALITY, for NOTHING but a little thanks and respect in return and you will have lost the one opportunity to financially bolster and possibly save this server.  I'm capable of 100 to 400 dollars PER MONTH to a server that DESERVES IT.. this one just disqualified itself today... unless you all decide to be 'lenient' and can show that you have  a heart and can forgive a one-time offense out of frustration for trying to understand something and being made out to look like a hackusator.  Bonzer is a .... LIAR and my own fac members hate him. They all say he's ... a bad word.
But because he's flaming the all -evil shrek who destroys factions and servers, it's all good. People are going to see how unfair and biased this place and run away and never come back and it's your own fault. You have 1.9 hours... choose wisely.

**Comment by OldDewd** [comment]
and I just told my wife what my intentions are.. about paying a server to pay people to be inclined to work and develop it and she's like 'You're sTILL trying to find some stupid minecraft serverto blow al your money on?  Why don't you take that job running the game room at the record store you helped open 3 years ago and stop playing with those children?"  My wife is wise.  So, I'm going to the record store tomorrow and secure that position, which will take away all my gaming time and give me even MORE money I can't find anything to spend on... joy.. :/ and the only time I have left for minecraft will be late-night and that's when my dutch friends play on their server and that's where I'll most likely live out the rest of my Minecraft days.. on some boring private server that only has people on at 3 am but they LIKE me and we get along and they work with me when I'm having a crisis and try to nurture good relationships so maybe I've found the server I can invest in after all.  Shame to be sending the money out of country when people here need it more.  I'm an easy person to get along with, as long as you're not my TEAMMATE and don't go making my private thoughts public for everyone to hate on.   Two things will come of this.. Jusa will come back and put everything right and prevent this from happening again, or Bonzer will lie to him, turn him against me too and I will have TRULY no reason to ever come back.  I can't join any other faction or novaria will rape me repeatedly for leaving them, and no one can protect me from Novaria in the server, so i can't function or do anything enjoyable.. at that point, it's complete and total frustration for me because this is the only server of it's kind that I can find (someone please redirect me to another server like this if one exists and you can be rid of me) and I finally learned the most of it so that I can develop my player and be competitive... and then all this.,. leaves me with absolutely NOTHING TO DO here, until Jusa gets back monday so you might as well ban me until MOnday because there will be nothing for me to do until then anyway.  What a cluster..... unbelievable.

**Comment by OldDewd** [comment]
andI was talking about monthly automatic draws, deposited directly into Ginger's account (or whoever's handling that)... not some payment I might make this month and not the next... It would be PERMANENT, until I decide I don't want to play here anymore... and with that kind of money to use for good, I could only see this place improving instead of imploding like it's doing.

**Comment by OldDewd** [comment]
this is my last comment on it all.  You people make me want to die.  You make me want to just lay down in my bed, close my eyes and hope I never wake up. or grab my .45 and speed it up.  Congratulations on losing another active 10+hour a day player.   I'm sure that's what you were trying to do, right?  Maybe even an assisted suicide in there.. that'd make everyone smile too, I imagine.  Thanks for taking the one thing away from me that was giving me joy in my otherwise shizzy life.

**Comment by OldDewd** [comment]
goodbye cruel world.
