### ISSUE TITLE
combat udmmy glitch

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#237]
combat dummies sometimes stay after logging out + they cut off peoples usersnames to the last letter of their name
so minewould be 8
because seamonster778
or fiercefigh(t) > t

**Comment by GingerWalnut** [comment]
The last letter thing is because of how names work in MC. I've moved the Combat Dummy tag to the front of the name so it should actually display the username. The other part is reported in multiple places, so I will close this issue
