### ISSUE TITLE
Issue with turrets

### ISSUE THREAD

**Issue by APnaptime** [GingerWalnut/SQBeyondPublic#239]
general issue of people getting stuck in turrets, have had an instance where someone was kicked for afk while in turret and turret thought player was still inside

**Comment by Jarkyc** [comment]
I mean just don’t afk in a turret? Although yea turrets do act weird, might look into it after I’m done with my current stuff

**Comment by GingerWalnut** [comment]
The issue with getting stuck in turrets is fixed.
