### ISSUE TITLE
ship data doesnt save over restarts

### ISSUE THREAD

**Issue by APnaptime** [GingerWalnut/SQBeyondPublic#241]
ships have to be redetected after a restart, this messes up capital ship claims, carrier ships and beam transporters

**Comment by APnaptime** [comment]
this seems to be an issue mainly with carriers

**Comment by Jarkyc** [comment]
Beam transporters are acting weird. They’re being rewritten. Dunno what’s happening with the other stuff

**Comment by GingerWalnut** [comment]
Could not reproduce
