### ISSUE TITLE
arenstad planet model changed

### ISSUE THREAD

**Issue by APnaptime** [GingerWalnut/SQBeyondPublic#243]
the planet model for arenstad used to be geographically detailed right after the update but it changed to a mass of white wool

**Comment by Jarkyc** [comment]
When did you notice this change. The other day ginger had to replace the model because it was just staying as a ring but I doubt he did just wool so I’ll ask him.

**Comment by GingerWalnut** [comment]
I didn't know that arenstad was like that. When I did the update, it seemed to corrupt some of the planet models. I probably have a copy somewhere else, but it isn't a high priority.

**Comment by icekoob** [comment]
izifo model is a mass of white wool
