### ISSUE TITLE
getting kicked resets tutorial progress

### ISSUE THREAD

**Issue by APnaptime** [GingerWalnut/SQBeyondPublic#244]
beezbo was kicked and had his tutorial revert to spawn in ship

**Comment by Seamonster778778778788** [comment]
don't kick new players right off the bat unless it's bad
relogging to reset tutorial is good for new players that happened to fly to
the world border some how

**Comment by GingerWalnut** [comment]
This is intended. The tutorial resets in case somethings goes wrong and new players relog or if they leave and then show back up a month later and don't remember the first half of the tutorial.
