### ISSUE TITLE
Bug: items acting weird

### ISSUE THREAD

**Issue by Elttob** [GingerWalnut/SQBeyondPublic#25]
As you move items around your inventory, they sometimes disappear on the client side.

Repro steps: move items around in your inventory, they should sometimes disappear but still be there when you click on the slot.

**Comment by GingerWalnut** [comment]
I think this might be fixed? Let me know if it still happens

**Comment by GingerWalnut** [comment]
nvm it started again

**Comment by GingerWalnut** [comment]
Finally actually fixed
