### ISSUE TITLE
Insane amount of mob spawns

### ISSUE THREAD

**Issue by fiercefight** [GingerWalnut/SQBeyondPublic#255]
This is happening on valadro, seems like there an excessive amount of mobs, also happening with aggressive mobs, not just passive ones. 
![2019-05-17_21 50 00](https://user-images.githubusercontent.com/9440176/57963120-cb020400-78ed-11e9-80c6-60e8bfabc725.png)

**Comment by GingerWalnut** [comment]
I think this has been fixed, let me know if it hasn't
