### ISSUE TITLE
cryopod issue

### ISSUE THREAD

**Issue by armbar2015** [GingerWalnut/SQBeyondPublic#258]
so this is something that happened. so after the update to 1.14 you were told to reclick/check cryopod. so i did that and i somehow sufficated in a wall (dont ask me how it just happened) and interestingly enough i did not respawn at my cryopod. just a minor issue and my friend said my name was still on cryopod so im just here thinking what goin on? this happened today (5/18/2019) at about 5:30 mountain time. just a small issue it may only be me and it may not have been checked/redone correctly when i did cryopod.

**Comment by Seamonster778778778788** [comment]
please ask a mod to teleport you back to your cryopod
