### ISSUE TITLE
cannot teleport to people that are not on your planet

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#259]
I could not teleport to Hail_Overl0rd while on yavar, I had to world tp to radawii for the teleport to work, otherwise it gave me this error
![image](https://user-images.githubusercontent.com/34897864/57976864-42986780-79b0-11e9-9926-5af738ea6117.png)

/tp2p works however

**Comment by Seamonster778778778788** [comment]
update: tp2p does not work for me. works for overcastniar

**Comment by GingerWalnut** [comment]
Essentials hasn't updated to 1.14 quite yet, so some of the commands are broken. In the next restart, there will be a /temptp command that will allow you to teleport to players.
