### ISSUE TITLE
sign data gets wiped sometimes

### ISSUE THREAD

**Issue by icekoob** [GingerWalnut/SQBeyondPublic#264]
yeah that happened when i went to space from a planet and my modules got messed up because of that

**Comment by icekoob** [comment]
dropper data also gets messed up. i.e i have 14/14 dropper spots on my ship. after i went to space it turned to 18/14

**Comment by BoyWonderFTW** [comment]
Ive noticed that the modules that get messed up are usually boarding ramps and slipdrives. In addition, slipdrive fuel seems to disappear after autopiloting randomly or traveling through a slipgate/sipspace

**Comment by Laserlance141** [comment]
Haven't seen it happen with boarding ramps, but it doesn't usually effect every slipdrive on a ship, only the one the fuel gets pulled from, and the slip drive with the blank sign still works until you click the sign, which updates it

**Comment by icekoob** [comment]
it affected my main slipdrive

**Comment by GingerWalnut** [comment]
This has been fixed

**Comment by icekoob** [comment]
still happening to my slipdrives
