### ISSUE TITLE
non-existent outposts prevents hq-reclaiming

### ISSUE THREAD

**Issue by icekoob** [GingerWalnut/SQBeyondPublic#265]
i literally don't have any outposts viewable on the dynmap and it says i have outposts on my faction description even though i did ./f declaimall. this prevents me from reclaiming my hq

**Comment by icekoob** [comment]
i mean a solution for my faction is to disband it and then have the reputation refunded as i believe this is only affecting RealStarline(coolhand24's faction) & OSHA(my faction)

**Comment by GingerWalnut** [comment]
Where should your outposts be?

**Comment by icekoob** [comment]
i have outposts on izifo, xira and yavar

**Comment by icekoob** [comment]
maybe just set the number of outposts that i have to zero?

**Comment by GingerWalnut** [comment]
It looks like to me that the outposts got auto-reclaimed

**Comment by icekoob** [comment]
wait so is the issue fixed for my faction(OSHA)?

**Comment by GingerWalnut** [comment]
Looks like it
