### ISSUE TITLE
droppers get messed up

### ISSUE THREAD

**Issue by icekoob** [GingerWalnut/SQBeyondPublic#269]
![2019-05-20_18 24 29](https://user-images.githubusercontent.com/12261784/58061751-2970f180-7b3d-11e9-8d14-74517a5ae39d.png)
sometimes after entering and exiting a world, your ship droppers get messed up. i had 14 droppers and the max amount of droppers is 14 on my man o war. after changing worlds, my droppers went up to 20 and it rendered my ship unpilotable. i was able to fix this issue via destroying all my droppers and then replacing them.

**Comment by GingerWalnut** [comment]
This should be fixed
