### ISSUE TITLE
Bows turn into rifles

### ISSUE THREAD

**Issue by TiatLief** [GingerWalnut/SQBeyondPublic#27]
Title

**Comment by TiatLief** [comment]
A message saying when reloading has complete would be useful, only other way to find out is to try shooting?

**Comment by TiatLief** [comment]
Also left clicking to force reload was a good feature we used to have.

**Comment by GingerWalnut** [comment]
Fixed.

If you are still holding the blaster it stops saying reloading...

left click is zoom so we can't do that.
