### ISSUE TITLE
suggestion: teliportation/ portal between points

### ISSUE THREAD

**Issue by armbar2015** [GingerWalnut/SQBeyondPublic#271]
so this is an interesting one that came to mind, a bit out there and i do not have any code or anything of that sort for this but it a neat idea.

so because sq is suppose to be futuristic with space ships and elevators and machines that can dig for you with giant gates to other star systems i was thinking of portals. this is going to be in 3 different sizes and only transports players with each of them having an eye of ender in there hand for this to work. this teleporter would have high building costs that are either expensive to supply for or hard to get. this is only for PLANETARY travel not to travel through space instantly (because that would be crazy op however maybe to other planets in the system but that would still be kinda powerful)

for the smallest teleporter, it will be in the shape of a cryopod with the exterior blocks being made of glass where the stone/wool is suppose to go. the interior blocks where the glass is supose to go the side walls need blocks of diamonds (5 total) and the top and bottom block is obsidian. then have a hopper on the back of it where the eye of ender goes. there will also be a door of any type. right above the hopper is where the sign will go for activation.

the next size up if a 2X2X2 room(2 top 2 side 2 bottom) this requires 11 diamond blocks, 8 obsidian, 2 doors, 1 hopper, and one sign.

the final size is a 5X5X5 room (honestly this is a bit overkill but it could be in there) this requires 1 door, 97 diamond blocks, 50 obsidian blocks, 1 hopper and one sign. this one however can go through the system and up to near by star systems where another one that the faction that built the first one goes.however this is a higher cost of 3 eye of ender to transport 1 person that far in such a big machine and that is 3 per person. there is also a risk factor that the farther you go the more likely your not to go through all the way (in other words there atoms get ripped apart in transportation causing death)

that is all if you have anything you would like to add put it in but that is my small suggestion for this.

**Comment by GingerWalnut** [comment]
As a standard rule, we don't do teleportation because it bypasses ships.
