### ISSUE TITLE
general Jane improvements

### ISSUE THREAD

**Issue by APnaptime** [GingerWalnut/SQBeyondPublic#274]
stuff like jane aquavo could give the current coords of a planet, gate or station, would make slipdrives easier to use
Jane iron planets could list a few planets with iron, same with other resources like animals or mobs
jane cryopod could redirect with link to the cryopod site

**Comment by Jarkyc** [comment]
I will not be personally doing this as I have other things to work on. However, with new Jane, everyone can add to it so mods can feel free to add it.
