### ISSUE TITLE
ships sometimes get cut in half/quarters 

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#278]
i dont know how to reproduce, might be on restarts
![image](https://user-images.githubusercontent.com/34897864/58212752-7c6db480-7cb5-11e9-89e2-10d60aa23a4a.png)

**Comment by APnaptime** [comment]
oh its my ship

**Comment by GingerWalnut** [comment]
Probably related to the crashing
