### ISSUE TITLE
Uh random tps into space? 

### ISSUE THREAD

**Issue by JUSAPlayer1** [GingerWalnut/SQBeyondPublic#281]
Twice now I've logged off on jurion and a few hours later I've logged back in and have been at the quol station..not sure how this happens but I relogged immediately and tested it and was still on the planet. Figured I should report it since it happened twice but I'm not sure how to reproduce it. I'll post another update if it happens again

**Comment by GingerWalnut** [comment]
I don't think this has happened to anyone lately
