### ISSUE TITLE
Faction access perms for outpost chunks are cleared during restarts

### ISSUE THREAD

**Issue by Laserlance141** [GingerWalnut/SQBeyondPublic#284]
Title, seems to have started sometime on 5/26

**Comment by GingerWalnut** [comment]
Does this still happen?

**Comment by Laserlance141** [comment]
I have no idea, I upped my person to member so they have normal access without the access command. I can try to re-add him to the chunk and see if it deletes again

**Comment by Seamonster778778778788** [comment]
@Laserlance141 update?

**Comment by Laserlance141** [comment]
Still happening, I added myself to a fac chunk that is also an outpost chunk, and when I checked today I was no longer added

**Comment by GingerWalnut** [comment]
Fixed.
