### ISSUE TITLE
Suggestion: Shipsize commands

### ISSUE THREAD

**Issue by LivesParkkk** [GingerWalnut/SQBeyondPublic#29]
It is frustrating not knowing how many blocks you are over when trying to build a ship. When you try to detect a new ship and it fails it should print the size of the ship in blocks, and while piloting there should be a /shipsize command that shows how many blocks, (and ideally what types of blocks) are part of the ship.

**Comment by GingerWalnut** [comment]
There is a command for ships while they are piloted (/ship info or /ship size)

**Comment by GingerWalnut** [comment]
Also, it is pretty close to impossible to tell you how many blocks you are over because it stops once it reaches the max size. Otherwise, it could accidentally detect way too much.
