### ISSUE TITLE
exponential ship shift flying

### ISSUE THREAD

**Issue by APnaptime** [GingerWalnut/SQBeyondPublic#294]
I was flying a frigate carrier out of arenstad, jumped from space in aren to y 150 syndicate station, afterwards I shift flew faster and faster the longer I held down the shift key, the bps did reset when I stopped shifting

**Comment by GingerWalnut** [comment]
Has this happened again recently?

**Comment by Seamonster778778778788** [comment]
@APnaptime ^

**Comment by APnaptime** [comment]
No
