### ISSUE TITLE
max sized carrier ship (frigate) gives error ship size is too big after unpiloting and repiloting (its an actual problem)

### ISSUE THREAD

**Issue by APnaptime** [GingerWalnut/SQBeyondPublic#296]
yes, but the ship works theoretically (ship size + carried size is less than max) but after piloting it and slipdriving it, after unpiloting the ship, I get the size error which should not happen

**Comment by GingerWalnut** [comment]
I've done some tweaking with carriers. Let me know if you encounter any more problems.
