### ISSUE TITLE
I got banned... sorry

### ISSUE THREAD

**Issue by jascrub** [GingerWalnut/SQBeyondPublic#297]
Im sorry but I said the N word, Im not racist and thought the server would censor it after my friend joined. I wont say it again and didnt know you could in the first place. Ive been playing on this server for years and think its a great concept, I wont let it happen again for sure. Also its not really an issue so sry for putting it in this forum but i dont see another place to put it. My username is Jascrub btw, my bad.

**Comment by Seamonster778778778788** [comment]
i have unbanned you, dont do it again

**Comment by Jarkyc** [comment]
Resolved.
