### ISSUE TITLE
Objective/Quest bug

### ISSUE THREAD

**Issue by EasternStandardHazen** [GingerWalnut/SQBeyondPublic#298]
The objective/quest players are given when they first join hasn't ended for me. I continue to get messages in the chat telling me to go to the ship spawners and buy a noobfighter even though I've done that and left spawn quite a while ago. The scoreboard also hasn't gone away. Not a big deal, but a bit irritating.

Thanks for reading

**Comment by GingerWalnut** [comment]
When did you first go to the ship spawner and buy a noobfighter?

**Comment by GingerWalnut** [comment]
Found the issue, fixed
