### ISSUE TITLE
general issues with ship blocks and armor blocks

### ISSUE THREAD

**Issue by APnaptime** [GingerWalnut/SQBeyondPublic#299]
smooth stone slabs are no longer armor
new blocks such as bamboo are counted as ship blocks
jack o lanterns are ship blocks

**Comment by APnaptime** [comment]
and new 1.14 blocks dont regen

**Comment by GingerWalnut** [comment]
All of these instances have been fixed. let me know if any other blocks need to be removed from the ship list
