### ISSUE TITLE
suggestion: weather on planets + cool mobs on rogue planets & deep space

### ISSUE THREAD

**Issue by icekoob** [GingerWalnut/SQBeyondPublic#304]
weather on planets would be nice hehe. i was messing on my creative server and i spawned in mobs riding other mobs(i.e strays on phantoms), and i believe that would make rogue planets a tad bit cooler and a bit more harder. deep space could be a space world that’s not viewable on the dynmap full of asteroids and rogue planets, and enterable from the world border in the space world. slipdrive could be disabled in this world and radars would be useful for hunting people down.

**Comment by icekoob** [comment]
sorry for poor formatting, i’m on my phone and i’ll edit it once i get back to my computer

**Comment by icekoob** [comment]
crap

**Comment by GingerWalnut** [comment]
Not planning on adding deep space. Arenstad and Mardos now have weather.
