### ISSUE TITLE
Unable to complete contracts in parts

### ISSUE THREAD

**Issue by LivesParkkk** [GingerWalnut/SQBeyondPublic#31]
You need to have the full number of items a contract requests in your ship inventories at once to complete it. You are unable to complete in parts. This is bad, meaning you need to have a cargo bay to even complete a basic contract.

**Comment by GingerWalnut** [comment]
This is semi-intended. I will consider changing it, but I'm leaning towards no atm.

**Comment by GingerWalnut** [comment]
This will not change for now. If you have a good argument for why it should be, let me know.
