### ISSUE TITLE
concerns with void

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#310]
bamboo can grow in void
so can sweet berries
cactus too
bamboo can be used as fuel (i think)
disable sq tech in void, cobble farms can be used to create infinite xp farms in voids

possibly disable water and lava spread in void to not allow cobble farms?

**Comment by GingerWalnut** [comment]
Should be fixed for next restart. I will probably not disable sq tech though
