### ISSUE TITLE
bruh moment

### ISSUE THREAD

**Issue by jascrub** [GingerWalnut/SQBeyondPublic#316]
bruh moment

**Comment by Seamonster778778778788** [comment]
you joined on multiple accounts and started using racial slurs aftre joining

**Comment by jascrub** [comment]
That wasn't me...

**Comment by Seamonster778778778788** [comment]
i have increased all of your bans to perm so they all look similar, is that ok?

**Comment by jascrub** [comment]
why though?

**Comment by Seamonster778778778788** [comment]
lying

**Comment by Seamonster778778778788** [comment]
you are welcome, have a nice day

**Comment by jascrub** [comment]
wow

**Comment by Seamonster778778778788** [comment]
also I have seen all of you hack on multiple occasions after watching you for quite a while

**Comment by jascrub** [comment]
![download](https://user-images.githubusercontent.com/31397861/59011098-2b070e80-87f9-11e9-9f93-a14e510004c1.jpg)

**Comment by Seamonster778778778788** [comment]
clearly
i have recorded occasions of all of u hacking @Jarkyc @GingerWalnut fix pls

**Comment by jascrub** [comment]
bruh moment

**Comment by Seamonster778778778788** [comment]
its ok, maybe not hack on every single game

**Comment by jascrub** [comment]
i dont but its ok

**Comment by jascrub** [comment]
bruh moment

**Comment by jascrub** [comment]
> bruh moment

bruh moment

**Comment by jascrub** [comment]
> > bruh moment
> 
> bruh moment

bruh moment
