### ISSUE TITLE
Silly Flying Blocks

### ISSUE THREAD

**Issue by grimreeper132** [GingerWalnut/SQBeyondPublic#318]
Why are the brick blocks flyable blocks considering that they are used for ship replicators which makes redetecting them after replication a real pain.
Also why is scaffolding a ship block considering it is used for construction as well

**Comment by Seamonster778778778788** [comment]
I don't think that's intended

**Comment by grimreeper132** [comment]
I assume it's not meant to be happening that, but it is happening

**Comment by GingerWalnut** [comment]
Fixed for next restart
