### ISSUE TITLE
Improb drive arrows stay if you unpilot during spool

### ISSUE THREAD

**Issue by TiatLief** [GingerWalnut/SQBeyondPublic#32]
Title, possibly allow right clicking the sign again to disable the spool, not sure if you fixed the same bug for slipdrives earlier.

**Comment by TiatLief** [comment]
Maybe don't show the arrow at all so players do not reset the drive until they get the direction they want?

**Comment by GingerWalnut** [comment]
Fixed for improbability and slip drives for next restart.
