### ISSUE TITLE
grace period doesnt respect bows/apturrets/blasters/etc

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#321]

**Comment by Seamonster778778778788** [comment]
and the person with grace can hit people

**Comment by GingerWalnut** [comment]
Can the person with grace hit people all the time, or only with bows/apturrets/blasters?

**Comment by GingerWalnut** [comment]
Grace period should now work with bows/apturrets/blasters and people with grace period can no longer hit people
