### ISSUE TITLE
random blocks disappeared 

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#324]
similar to ice's issue (couldn't find it) 
![image](https://user-images.githubusercontent.com/34897864/59128414-99e68380-892f-11e9-8451-970a8cfbff97.png)
![image](https://user-images.githubusercontent.com/34897864/59128422-9eab3780-892f-11e9-9e03-1b8a81db413f.png)

**Comment by GingerWalnut** [comment]
Any idea what caused it? Is there a possibility that the ship was flown into a nano mine field?

**Comment by Seamonster778778778788** [comment]
no he never left the planet

**Comment by icekoob** [comment]
it’s really weird

**Comment by Seamonster778778778788** [comment]
#158 Same issue, refer to 158

**Comment by Jarkyc** [comment]
Old
