### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by Yargon-Kerman** [GingerWalnut/SQBeyondPublic#327]
After playing for a short while and coming from previous versions (playing 2.0 & being one of the most active players on 3.0), a few noteable things have come up that i would like to bring to the attention of the staff:

1] Uses for money
It has become somewhat obvious that money looses all value after a certain point. One thing that could be useful is the ability to simply pay a significant amount of money to complete a contract.
It would also be useful to be able to pay a small fee to refresh your available contracts.
Additionally, buying some blocks would be useful, such as buying sponges, pistons, or other blocks from venders at the various stations.
Another use for money would be temporary faction-wide boons, such as buying an XP bonus, ship speed boost or mining speed boost for all faction members that lasts for a short time, such as an hour. The price of this could be dependent on your faction rank and number of faction members, but ought be relatively expensive to provide an end game money sink. I would also caution away from making any effects that affect combat directly, to avoid a near "pay to win" aspect.
Additionally, the price of faction land could scale proportionally to the number of chunks already claimed after a certain amount (perhaps based on the number of players or faction rank) to add a money sink to large factions whist allowing small factions to grow freely.

2] Siege time to 30 mins
Sieges last for an hour currently, this, combined with the charge up time, and the fact they can be preceded with a raid, this can force players to be online for around two hours. Considering not all players can dedicate two hours to the game at the drop of a hat, this seems far too long. Perhapse lowering the time of a siege to half an hour and the charge up to 10 minutes may help with this?

3] Contracts remove instability
Instability currently doesn't ever fall unless you are also a pirate. This means that any players not willing to raid must either build exclusively in the void or never progress past a level 4 faction or else they'll face eventually loosing everything. This is a significant problem for "colonist" player. If completing a contract reduced a factions instability by 1 or 2 points, the colonist type players would be able to safely progress without sustaining themselves exclusively inside the void.

4] Instability dropping over time.
Additionally, Instability could passively drop over time. This would only really work as a complimentary feature to contracts removing instability, but it would make it so that a single raid a month won't eventually cause the downfall of a massive faction, even if they don't complete contracts.

5] Raiding/Sieging  sharing a cool down.
It seems strange to me that Raids and Sieges have cool downs but don't share one. If a player raids or sieges another faction, they should have a cool down of a few hours before they can raid or siege again.

**Comment by Seamonster778778778788** [comment]
me agree with all

**Comment by Yargon-Kerman** [comment]
Just writing a quick addition to expand upon the reasons I'm suggesting #3, #4, and #5.

Starquest has always had Colonist and Pirate players, they're not as black and white as they used to be (or red and blue i suppose,) but they still exist. Pirate players are usually talented, or at least competent at PvP and SvS and have little to no qualms taking things from other players if they get their hands on it. Colonist players are usually not as capable at PvP or SvS and often dislike taking things from others but spend much longer building huge farms, and bases.

Unfortunately, under the current system if a pirate chooses to raid a base, they may be capable of doing so with little to no resistance as they are far more likely to win any engagement (and the colonists know this). This means that it is possible for a pirate to rack up a significant amount of instability in any given enemy faction. This instability won't leave, ever. This means that it could be possible for a pirate faction to raid their opponents and not "spend" any instability until they can overclaim their entire base in a single siege.

I'll give an example here, including a solution (and a workaround for that solution) proposed by a few people when asked about this:

My faction currently has 128 max faction power, and 57 land claimed currently. We'll assume that we claim a 1 chunk outpost making that 58 land, with little to nothing in it because that's a simple solution that I've heard a few people suggest.
Now assume a two man faction decides they dislike mine, and are fully fledged pirates capable of beating us in 99% of engagements. They decided to both Raid and Siege us as much as they can in a day, every day. with the 24 hours cool downs, that allows them to raid and siege each once per day. If they have both players online for both, and pillage as much as possible, they can give us a theoretical 75 instability per day. That's a little unlikely, but 65 is perfectly reasonable. that's 130 instability each day.
Now assume they choose to raid again the second day and claim another 130 instability (They could pillage far less, each day, and just spend more days doing it).
We have one outpost, and over claiming that would loose us 50 instability, but they have 260 at this point. They can overclaim it, that's 51 instability gone, leaving us at 209. That's enough to overclaim our entire base of 57 remaining chunks in a single raid.

The major problem with this, is there's not a damned thing we can do about it.

**Comment by icekoob** [comment]
yeah i have 106 instability and i have no way of getting rid of it unless i attack my allies or get raided more. a passive sink would be nice too bc i haven’t been attacked in like a month

**Comment by GingerWalnut** [comment]
1. Money is now useful for getting more land which helps with council stuff
2. Sieges have been removed
3. Instability has been removed
4. See above
5. See above
