### ISSUE TITLE
re-add old beam transporters

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#328]
the new ones dont work and the old ones were cool and lifted u up slowly with particles 
the new ones just tp u
and theres no wiki page for the new ones

**Comment by APnaptime** [comment]
but I hear the new ones dont have to redetect and dont cause particle lag

**Comment by Seamonster778778778788** [comment]
they don't function

**Comment by Jarkyc** [comment]
They were just working, got word last night they weren’t. Will tale a look when I get home

**Comment by icekoob** [comment]
they work for me

**Comment by Jarkyc** [comment]
Problem found. Scheduled to fix.
