### ISSUE TITLE
enderchest

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#329]
i put an ender chest down in my ship with the intention to break it after im done, and I forgot about it and flew off, and it is just.. gone?

**Comment by Jarkyc** [comment]
Ender chests don’t fly iirc

**Comment by Seamonster778778778788** [comment]
Yes I am aware. The problem is what is stated in the post.

**Comment by GingerWalnut** [comment]
Either there was a bug with chunk saving, or you lost it.
