### ISSUE TITLE
an issue I have found after watching 5 people raid a base

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#331]
Regen times are WAY too short to actually be useful

by the time you're somewhere important, the part where you started blowing up is already regening

I suggest extending the timer during raids to something like 15 minutes to help solve this

**Comment by Jarkyc** [comment]
I think refers should just be turned off in factions being raided or sieges, until the raid or siege is over, then stuff will start regening.

**Comment by GingerWalnut** [comment]
No longer relevant.
