### ISSUE TITLE
suggestion: endgame content

### ISSUE THREAD

**Issue by armbar2015** [GingerWalnut/SQBeyondPublic#333]
so this is gonna kinda be a list cause after flagship i dont really see anywhere to go but down because then what?  this is gonna be a small list of things to add for end game content.

1: another system for end game.
so what i mean by this is a system possibly on the north west or east side of the map and this system is filled with more dangers and good loot. one planet is basically i giant maze with a high level of wither and dragon spawn. however the maze does have some top gear loot that could compare to the forge. other planets are basically supose to be very challanging and can destroy capital ships with ease on these planets.

2: build-able stations.
so this is a station a faction and build at or above rank 15 and this station will be able to act like a hub for other players and also allow recruitment for this faction and other faction things.

3: weapons of mass destruction (maybe)

now this is an idea that could be in the game, but will not really be usable in the games current state. these weapons are on the level of warheads and planetary lasers. these will require a lot of materials to make and could malfunction at random and destroy themselves. however these weapons can perm destroy blocks in mass amounts and ignore faction claims.
(this is the reason i thought it would be basically op in every aspect of the game at its current state, because most bases are above or partially above ground which would make this very powerful rn.

**Comment by Jarkyc** [comment]
It would be a bad idea to even give players the option of weapons of mass destruction

**Comment by armbar2015** [comment]
Yeah I put in probably a bad idea. But what about the other 2 suggestions I pointed out?

**Comment by GingerWalnut** [comment]
1. We are not planning on adding another system at this time.
2. You can already create capital ships which you can use as a station
3. Bypassing faction claims is a no no
