### ISSUE TITLE
wiki needs overhaul

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#336]
wiki needs update to faction info, overclaiming, instability, etc
ship class information has been changed, everything

**Comment by Jarkyc** [comment]
You know that guy from frosty the snowman who runs away and is like saying “busy busy busy”. Yea that.

**Comment by Seamonster778778778788** [comment]
you know that good Jr dev
I don't either

**Comment by icekoob** [comment]
bruh i cant edit the wiki pls fix

**Comment by Liggo** [comment]
Switched to GitHub , jarky did good job
