### ISSUE TITLE
cant over claim a level 5 faction

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#339]
we got hellsing to have more instability than power, and when we tried to overclaim, it said he wasnt a high enough rank
![image](https://user-images.githubusercontent.com/34897864/59241570-d33c1f00-8bcd-11e9-8dc8-ec2e8da1d6cd.png)

**Comment by GingerWalnut** [comment]
This is going to be irrelevant soon
