### ISSUE TITLE
SQ Tech Machines not giving blocks back if block is moving

### ISSUE THREAD

**Issue by Laserlance141** [GingerWalnut/SQBeyondPublic#34]
So, If a piston is pushing a block when the SQ Tech Machine tries to break it, then it does not give the block back. This is fairly easy to see by comparing the two example machines in the Screenshot breaking blocks. The one on the right pushes a block in front to the breaker each cycle, making sure that there is never a moving block in front of the breaker. This one returns all the blocks placed. The one on the left just pushes them in as fast as possible, which means that sometimes the block in front of the breaker is moving when it activates. This one looses blocks as it goes.
I think a fix might be making the breaker unable to break block 42 (or whatever the moving block thing has turned into after 1.13).

![2019-02-24_16 57 20](https://user-images.githubusercontent.com/13091148/53308465-6f782b00-3856-11e9-99e9-8af2c2cc7436.png)

**Comment by Laserlance141** [comment]
Probably also happens with Diamond blocks breaking, make sure to apply to both machine parts

**Comment by GingerWalnut** [comment]
Fixed for next restart
