### ISSUE TITLE
add a /warn feature

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#340]
warning would be nice to keep track of if you told someone not to do something, etc

making it appear with the /title text like sq restarting in red or something similar would be a good way as well

**Comment by Jarkyc** [comment]
Have been thinking about doing this. Possibly will now.

**Comment by Jarkyc** [comment]
I will be making a staff tools plugin containing stuff like warns and such. That will be done when I am done with the other dev stuff. I have this written down in my notes, so I will be closing this.
