### ISSUE TITLE
shield generators are completely useless

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#347]
i do not think anyone has even made and kept it, it serves no purpose and has no advantages over the other auxiliary modules to even consider it, maybe change how it works

**Comment by icekoob** [comment]
BRUH AND LASER BEANS

**Comment by icekoob** [comment]
AND SPEED BOOSTERS

**Comment by icekoob** [comment]
HARVESTERS

**Comment by Pairjax** [comment]
Approved. Ship combat will be changing drastically, as I have already said.
