### ISSUE TITLE
Staff abuse 

### ISSUE THREAD

**Issue by coolman422** [GingerWalnut/SQBeyondPublic#355]
OK so pretty much me and two of my friends were getting harassed on the server for no reason by mods and powerful players. My two friends decided to start hacking and got banned i litterly did nothing wrong and got a perm ban like rely?!?!?! It says under my reason for ban is "Hacking and sending bad messages to staff" I never once messaged staff and i never hacked, i dont even have minecraft hacks downloaded. This was a clearly staff abuse on the server, i later joined the discord to try and ask why i received a perm ban and asked if it could be redecued(or taken off cuz i litterly did nouithng) and then got immediately ban form the discord as well.

**Comment by Seamonster778778778788** [comment]
well I'll tell you 
1. You messaged the wrong discord staff member with your intended message. You linked many personal pages to your discord which led me to discover it was you.
2. You all hacked. Those of you with steam linked to your discord, you have been vac banned. 
3. One that goes by Ian, even has his youtube channel linked but it seems like that account was suspended.
4. You were all hacking casually around your base, fly hacks, no fall, glide, everything. 
5. You were all nothing but nuisances to the server and one of you repeatedly joined on alts and used slurs. 
6. This is not a ban appeal page. You are permanently gone. You shouldn't have broken rules.
