### ISSUE TITLE
SQ machines disappeared

### ISSUE THREAD

**Issue by fiercedude** [GingerWalnut/SQBeyondPublic#359]
I was mining with some SQtech machines for stone. When I finished mining, I made 18 mini-machines which I use simply to transport the materials back to base. I sent the machines back in 2 trips, as I only had enough coal to send 4 back the first time. I then came back and sent the rest back. Before I went offpline I made sure all were back at my base, protected in my faction claim. When I came back online this morning, only the four that I sent on the first trip were there, the rest were missing. Additionally, on the way back to my base the machines went through a river and left a pocket of air. While there are pockets of air from the 4 still here, there is no evidence that the 14 machines that went missing passed through the water, even though I saw them do it. When I went to where the drills had stopped drilling and I had started sending the machines back, there was no sign of the machines. It's like the never existed. I lost probably around 60+ stacks of stone because of this. If it helps, I logged off around midnight, so maybe the server restarting had something to do with it. 

![2019-06-19_09 42 48](https://user-images.githubusercontent.com/19196262/59771706-4a318180-9278-11e9-819b-a9434bab9864.png)
Screenshot of machines at my base. Only 4 are there. the other 14 are missing.

![2019-06-19_09 43 18](https://user-images.githubusercontent.com/19196262/59771707-4a318180-9278-11e9-80c1-ec1d558d8641.png)
Screenshot of the water. Only the hole left by the 4 remaining drills is there.

![2019-06-19_09 44 11](https://user-images.githubusercontent.com/19196262/59771708-4a318180-9278-11e9-8d93-5495e26a2457.png)
The site where I stopped drilling and made the machines. They aren't there either.

**Comment by Seamonster778778778788** [comment]
@fiercedude any recent cases?

**Comment by Jarkyc** [comment]
No response, hasn't been reported in a while.
