### ISSUE TITLE
new mobs on valadro spawned

### ISSUE THREAD

**Issue by fiercefight** [GingerWalnut/SQBeyondPublic#363]
new mobs from the village and pillage update were spawning on valadro

**Comment by Seamonster778778778788** [comment]
this is happening everywhere

**Comment by Seamonster778778778788** [comment]
there (was) trading llamas that spawned on tyder, but the illagers and raids maybe spawning because logout dummies are villagers

**Comment by icekoob** [comment]
there used to be trader llamas on Beksyttt too
