### ISSUE TITLE
Suggestion: data core consequences.

### ISSUE THREAD

**Issue by PickyIcky2** [GingerWalnut/SQBeyondPublic#368]
I think that having no consequence to having your data core get stolen is kind of dumb, it's hard to tell whether you're abusing data cores and will also cause people to not care about them, there should be some sort of consequence. I was thinking that it would be cool if you lose power/infractions if you lose your data core. because that should be an important part of your ship that you don't want people to steal.

**Comment by Seamonster778778778788** [comment]
Mods have ways of knowing if you abuse data cores ^^

**Comment by Pairjax** [comment]
Denied. Punishes new players if they lose their data core.
