### ISSUE TITLE
Text going off screen for contracts

### ISSUE THREAD

**Issue by JC3371** [GingerWalnut/SQBeyondPublic#37]
Text is going off screen for digitallia contracts 
![2019-02-24_18 29 09](https://user-images.githubusercontent.com/19299597/53310524-1a421680-3862-11e9-9abf-40eb9fcbd8b9.png)
![2019-02-24_18 29 08](https://user-images.githubusercontent.com/19299597/53310525-1a421680-3862-11e9-87a0-3a4f9c52bc02.png)
![2019-02-24_18 29 06](https://user-images.githubusercontent.com/19299597/53310526-1a421680-3862-11e9-90a9-390617246583.png)

Same thing for syndicate contracts
![2019-02-24_18 34 01](https://user-images.githubusercontent.com/19299597/53310811-35615600-3863-11e9-81ad-ff9b52d8420d.png)
![2019-02-24_18 33 59](https://user-images.githubusercontent.com/19299597/53310812-35615600-3863-11e9-80fd-e36f76032d2b.png)
![2019-02-24_18 33 57](https://user-images.githubusercontent.com/19299597/53310813-35615600-3863-11e9-8eee-a27e914fab91.png)

Same for quol security 
![2019-02-24_18 43 07](https://user-images.githubusercontent.com/19299597/53311304-3f845400-3865-11e9-93a2-51f23cb1c9e6.png)

**Comment by JC3371** [comment]
Fix for this is changing the gui scale to be smaller. Would be good if it can fit on screens with max gui and should solve the problem

**Comment by GingerWalnut** [comment]
Is this still an issue?

**Comment by Seamonster778778778788** [comment]
@JC3371

**Comment by JC3371** [comment]
It is but gets fixed if you make the gui scale smaller

**Comment by Seamonster778778778788** [comment]
What resolution of screen do you play on?

**Comment by JC3371** [comment]
2880 x 1800

**Comment by Seamonster778778778788** [comment]
That may be the issue because with my GUI scale on max it doesn't happen for me, with a 1080 x 1920.
