### ISSUE TITLE
BUG: Stuck in EVIL Turrets IMPORTANT

### ISSUE THREAD

**Issue by HailOVERLORD** [GingerWalnut/SQBeyondPublic#370]
I'm starting to become really frustrated when I enter a turret only to become stuck and waste a valuable sponge, or worse, have to call a mod to bail me out. This is especially frustrating in svs combat and flying. Attached is a picture of the message I get when I try to right click with a clock to exit. This happens to me about 75% of the time when I get into a turret. It is annoying to the point where I am afraid to even get into turrets to test them. PLEASE FIX THIS SOON! I HAVE LOST TOO MANY SPONGES!

![Minecraft 1 14 2 6_25_2019 6_15_14 PM](https://user-images.githubusercontent.com/49356843/60139894-4b314a00-9775-11e9-9ec6-272359568b88.png)

**Comment by icekoob** [comment]
it might be because ur clock/ship controller is in your off hand when ur in the turret

**Comment by HailOVERLORD** [comment]
It is not. I checked.

**Comment by icekoob** [comment]
how do you place your turrets? i don't get this bug

**Comment by Seamonster778778778788** [comment]
Has never happened to me, if you continue playing again provide screenshots of the not stuck in turret perspective.
