### ISSUE TITLE
make jammers turn off after a set amount of time to prevent people just leaving jammers on

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#378]

**Comment by icekoob** [comment]
this happens with cloaks except you’re uncloaked and you use up your cloaking time

**Comment by GingerWalnut** [comment]
Next update, jammers and other modules are going to turn off automatically when a ship unpilots. Technically speaking, they didn't do anything while the ship was unpiloted, but it should prevent people from not knowing a jammer is on.
