### ISSUE TITLE
Explosions enabled at Defalos Mining Station

### ISSUE THREAD

**Issue by NovusInventorMan** [GingerWalnut/SQBeyondPublic#379]
Synopsis:
I landed on the edge of the Defalos pad, and unpiloted the ship (I am a ranger), Usaid2002 then came over and used the turret in my ship, blowing it up. He then tried to fire on the ship with cannons, but those explosions were blocked.

I don't know if the ship shield deployed and interfered with the station region, or if the station region itself is messed up, or what.

Turret explosions of course seem to be calculated differently than cannon explosions - could the event intercept for turret explosions just be missing?

I have not tested this in any other regions.

**Comment by Seamonster778778778788** [comment]
Not sure on the status of turning off explosions in contract stations, if its still wonky or not
