### ISSUE TITLE
enable weather on planets with snow

### ISSUE THREAD

**Issue by icekoob** [GingerWalnut/SQBeyondPublic#387]
enabling weather on yavar, arenstad, mardos would be cool bc in 3.0 eratoss had snowy weather, plus when snow gets manually removed by players it kinda looks ugly and it would be nice having snow to replace the missing snow. also it wouldn't hurt to have occasional weather on some tropical planets :p

**Comment by GingerWalnut** [comment]
Done for Arenstad and Mardos next restart
