### ISSUE TITLE
Weird issue on Izifo

### ISSUE THREAD

**Issue by mcneproj** [GingerWalnut/SQBeyondPublic#388]
Ok so I went to Izifo earlier today and got kicked. Kept trying to relog and always got the java exception about connection forced closed by host. I went on the discord looking for help and Tiat was able to fly me and my ship back into space. Now everything works as usual. Fixed just like that. Im not sure what happened but what i think was my connection. I have rural internet and it fluctuates between 10-20mbps. That and maybe all the trees on Izifo lagged me out possibly. Seems this was totally client side. And we thought it would be worth mentioning. On a side not im staying far away from Izifo lol. 

Edit: Also would like to add it resulted in a kick from minechat app as well. Dont know if that helps.

**Comment by Seamonster778778778788** [comment]
Could you provide logs or any more information? What side of the planet did you enter from? Have you tried entering again recently? @mcneproj

**Comment by Jarkyc** [comment]
No response, hasn't happened in a long time.
