### ISSUE TITLE
Droppers not feeding furnaces sq tech

### ISSUE THREAD

**Issue by Xanathar0** [GingerWalnut/SQBeyondPublic#389]
Droppers feed other inventory blocks but not furnaces. (I have a video of this but i cant attach it due to file limitations

**Comment by GingerWalnut** [comment]
As a temporary solution, try using feeding into hoppers that feed into the furnace.

**Comment by Xanathar0** [comment]
i would but im using an sq tech machine make a huge line of 1x3 miners and was trying to integrate  auto feeding into the machine
![2019-07-15_10 44 34](https://user-images.githubusercontent.com/52472148/61581140-126c6280-aae0-11e9-91ee-0bad08e5584d.png)
![2019-07-20_11 08 48](https://user-images.githubusercontent.com/52472148/61581141-126c6280-aae0-11e9-94f6-7a18c05b0d7d.png)
![2019-07-20_11 10 09](https://user-images.githubusercontent.com/52472148/61581142-126c6280-aae0-11e9-9237-6e404b732589.png)
![2019-07-20_11 11 08](https://user-images.githubusercontent.com/52472148/61581143-1304f900-aae0-11e9-815d-2cfdba0d14d6.png)
in the new one the sponges are replaced by iron blocks

**Comment by GingerWalnut** [comment]
Fixed for next restart
