### ISSUE TITLE
You can pilot a ship, even if your name isn’t on the sign.

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#39]
I don’t know if this is intended, but even if your name isn’t on the ship sign, you can pilot it.

**Comment by GingerWalnut** [comment]
So, this has been semi-fixed. Before, everyone, by default had permissions to pilot ships. You could change those settings in the permissions part of the starship gui. However, I have changed the default default permissions to not have those permissions. The old ships will still be affected, but new ships won't allow other people to pilot your ship unless you allow them to.
