### ISSUE TITLE
A forced disconnection every time I enter a planet (please help me out)

### ISSUE THREAD

**Issue by Tibarious** [GingerWalnut/SQBeyondPublic#390]
Every damn time I enter a planet, I get disconnected immediately which is SO annoying. This annoying message keeps popping out:

                                                               Connection Lost
Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host

PLEASE help me out, I can't even enjoy playing in the server.

Notes: When I am in Space, everything's fine, but once I enter a planet, I cant use either commands, cant see what I entered in chat, and cant interact with any signs while im in the ship

**Comment by GingerWalnut** [comment]
This sounds like it is probably a client-side issue because no one else is experiencing this issue. How good is your computer and internet connection?

**Comment by Tibarious** [comment]
Well the PC I am using (I do not know the exact details of it, but) is actually robust and well performing. I guess the only thing left is the Internet connectivity, which is actually not so good. Anyway, thanks a lot GingerWalnut for helping me out understand this problem. I guess I'll have to improve my Internet connection. Thanks!

**Comment by GingerWalnut** [comment]
You might try reducing your render distance. We have temporarily increased it server-side while we are doing some recording, and a bigger render distance will put more strain on your internet.
