### ISSUE TITLE
Too many mobs spawning on Duru

### ISSUE THREAD

**Issue by JC3371** [GingerWalnut/SQBeyondPublic#396]
![2019-07-30_12 09 54](https://user-images.githubusercontent.com/19299597/62157871-fb3d2a00-b2c2-11e9-893c-886571743a2d.png)
Title ^
![2019-07-30_12 02 24](https://user-images.githubusercontent.com/19299597/62157446-0b083e80-b2c2-11e9-8144-7ffa805ac4ae.png)
![2019-07-30_11 59 27](https://user-images.githubusercontent.com/19299597/62157447-0b083e80-b2c2-11e9-87bf-71291f3e78b7.png)
![2019-07-30_11 59 24](https://user-images.githubusercontent.com/19299597/62157448-0b083e80-b2c2-11e9-8ae8-c2bc2ed18b85.png)

**Comment by GingerWalnut** [comment]
Hostile mobs spawns will be reduced next restart
