### ISSUE TITLE
Capital ship claim fix isnt fixed

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#397]
![image](https://user-images.githubusercontent.com/34897864/62271863-4f4d2900-b3ff-11e9-9154-d2528ee1108d.png)
I piloted and it still doesn't unclaim

**Comment by GingerWalnut** [comment]
Was the capital ship unpiloted after or before the fix?

**Comment by Seamonster778778778788** [comment]
After

**Comment by GingerWalnut** [comment]
Actually fixed this time.
