### ISSUE TITLE
Sugestion: Have the ability to document anomalies.

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#40]
If you discover an anomaly, you can use the radar to “document” it. This basically just gives a location on dynmap telling people what the anomaly is and where it is. It also pings in chat:”(name) has documented (anomaly).” It can be fully optional incase you don’t want to give away the secret.

**Comment by GingerWalnut** [comment]
This has kinda been added with the new anomaly discovery mechanic
