### ISSUE TITLE
SQTech sorter

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#403]
Make an SQ sorter in order to sort items better than a vanilla sorting system
My idea:
![image](https://user-images.githubusercontent.com/34897864/63229093-35af2e00-c1c2-11e9-9a01-7e1ce4239c42.png)
(hopper facing into emerald)
The item to be put in the chest can be put in the dropper, and the items entering the system will skip the dropper and insert into the chest automatically while leaving the item to sort in the dropper
It would sort all of these items into the chest
![image](https://user-images.githubusercontent.com/34897864/63229110-5bd4ce00-c1c2-11e9-9eec-60984361bffb.png)
This would allow for a lot of automation and easy sorting, while you could also use redstone to automatically change what items ARE sorted

**Comment by Pairjax** [comment]
Approved. Will be added in the overall changes to SQTech & SQMegatech.
