### ISSUE TITLE
failed faction void stuff?

### ISSUE THREAD

**Issue by armbar2015** [GingerWalnut/SQBeyondPublic#409]
well, what happens to the stuff that is in a faction void? what happens to it? my guess is that it just stays there, to never be used again. now, this idea is something that will free up some space in the void, and lets that stuff be used.

my solution/idea is to auction off the stuff in there void. this would be only for faction void and not personal void. basically the time auction will start will be announced, and players will be able to put bids on the items in the void. however they also need to be able to pay for it.

**Comment by Liggo** [comment]
Voids no longer exist
