### ISSUE TITLE
/ship info lists dropper count incorrectly for barrels

### ISSUE THREAD

**Issue by Laserlance141** [GingerWalnut/SQBeyondPublic#410]
Barrels are suppose to count for 3 droppers, and they do (from what i've seen), but in the ship info menu, they show up as one dropper, leaving to confusion. Also possibly change the dropper name to something like Storage blocks or containers, as droppers are not the only things that counts that number up and may cause confusion for some newer players

**Comment by GingerWalnut** [comment]
FIxed for next restart
