### ISSUE TITLE
Elevator broken in a specific 4x4

### ISSUE THREAD

**Issue by Hitmontipx** [GingerWalnut/SQBeyondPublic#428]
Happened 6/10/19 at roughly 23:00 BST
Can't reproduce

Was dicking around with a boat on the elevator and it deleted some glass. After replacing it the elevator doesn't work. Elevators placed by us work elsewhere, just not in the 4x4 it broke in.

**Comment by Seamonster778778778788** [comment]
Elevators is not our plugin, however you can try moving the iron base up or down to see if it fixes it.
