### ISSUE TITLE
Crashing Ships

### ISSUE THREAD

**Issue by Pr1ckl3s** [GingerWalnut/SQBeyondPublic#434]
Obviously, this wouldn't work in space, but maybe ships could "crash" when they lose most of their hp/blocks, uncontrollably diving toward the ground and exploding. It'd make sense and would keep the skies clear, instead of having floating wreckage lying around.

**Comment by Pairjax** [comment]
Rejected. Actually a pretty good idea, but it has a lot of technical details about the idea that could add a lot of work. We'll try and solve the issue of random wreckage lying around some other way, but I'll keep it in mind.
