### ISSUE TITLE
Trees & Crops

### ISSUE THREAD

**Issue by ShadowHawk50** [GingerWalnut/SQBeyondPublic#436]
I think that wheat should grow on all planets so people don't starve and because grass grows on them & that trees should also grow on all planets so people can actually do things.

**Comment by menonamed** [comment]
Personally, I think this is the opposite of what we need. The spread of resources is perfectly balanced, and if you are having trouble with food, it encourages trading or traveling, rather then sitting around waiting for wheat to grow.

**Comment by Jarkyc** [comment]
Trees are supposed to grow on all planets. They were bugged, they are now fixed.
