### ISSUE TITLE
Vertical harvesters dont work

### ISSUE THREAD

**Issue by HTCaveman** [GingerWalnut/SQBeyondPublic#437]
I just built a new ship but vertical harvesters dont seem to work. I read the entire wiki of it, but when i put it on my ship it does not fire or harvest blocks, doesnt even make the firing sound.
Ive tried the horizontal harvester and it works fine, no problems. Ive used the /blueprint for the vert harvester yet it didnt work either.
I'm not sure if I'm dumb or if its broken, but im posting here.

**Comment by GingerWalnut** [comment]
Could not reproduce (Although there was a bug with harvesters that prevented them from picking up blocks that you couldn't get drops from with a hand).
