### ISSUE TITLE
Sq tech drills not collecting what it mines

### ISSUE THREAD

**Issue by fiercedude** [GingerWalnut/SQBeyondPublic#439]
I just made a 3x3 sqtech drill and drilled a tunnel through a mountain. When I was done, I checked the  droppers and all that was collected was some dirt and gravel. There was no cobble or coal.

**Comment by Seamonster778778778788** [comment]
sqtech has problems putting materials into storage ^^ it drops with no storage

**Comment by GingerWalnut** [comment]
This has been fixed. The problem was that it was returning drops for breaking the blocks by hand. Now it will return drops for breaking blocks with a pickaxe.
