### ISSUE TITLE
Teleported to spawn on one heart

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#45]
There’s a plugin or something that’s making it so that when you have 1 heart, it teleports you to spawn. So instead of dying you get teleported with all your stuff.

**Comment by Jarkyc** [comment]
Nexeon, RunnerNum48, and Lives experienced this with me as we were PvPing

**Comment by GingerWalnut** [comment]
What planet was it on? Were you in a faction claim? Did it only happen with PvP? Did it give you a message?

**Comment by GingerWalnut** [comment]
Turns out this was in the void and it is working as intended.
