### ISSUE TITLE
cannons can break glass on slipspace portals

### ISSUE THREAD

**Issue by qq410219243** [GingerWalnut/SQBeyondPublic#451]
Hi,
When you get next to a slipspace portal and fire a cannon, it breaks the glass inside the portal. I don't know if it naturally regenerates because I haven't seen it again yet, but please fix this. Otherwise, there will be common holes inside of your portals.
Thanks.

**Comment by GingerWalnut** [comment]
They regenerate. Explosions are enabled to prevent players from just hiding at slipgates.
