### ISSUE TITLE
In slipspace but not really in slipspace

### ISSUE THREAD

**Issue by qq410219243** [GingerWalnut/SQBeyondPublic#452]
If you go to a slipspace portal, place a block but don't redetect the ship, it will not let you go to slipspace. However, it shows the slipspace transfer progress bar. At the end, it spits you out on the other side. So, you're stuck at one side of the portal, vulnerable to attack, then suddenly you teleport to the other side.

**Comment by Jarkyc** [comment]
This is actually caused by a problem where there is a block in the way of the slipspace world. I need to look into it.

**Comment by Jarkyc** [comment]
Hasn't been a problem for a while.
