### ISSUE TITLE
Corporation / Spawn Landing pads too small

### ISSUE THREAD

**Issue by breadmiester** [GingerWalnut/SQBeyondPublic#453]
As player's get larger ship sizes, landing at many stations becomes a hassle due to landing pads being ridiculously small, or spawn port being too short to allow bigger ships in to pick players up and redeem insurance claims. 

Of course, players can EVA to the station, but it's slow and un-immersive, especially if players need to make multiple trips from station to ship. The act of perching your ship on a tiny edge is also a bit cumbersome, which is what happens most often.

Just some minor extensions to current landing pads are all that is necessary to correct this issue and would greatly improve user experience with popular and small stations.

![2019-12-31_15 19 10](https://user-images.githubusercontent.com/7785815/71633579-0df5bb00-2be3-11ea-84fe-2ab8fb789a14.png)

**Comment by Seamonster778778778788** [comment]
docking toob

**Comment by GingerWalnut** [comment]
^
