### ISSUE TITLE
rotation can sometimes change your position in your ship trapping you outside your cockpit 

### ISSUE THREAD

**Issue by TiatLief** [GingerWalnut/SQBeyondPublic#455]

**Comment by Jarkyc** [comment]
When you get pulled out of slip by a hammer something similar happens. You are still piloting you’re ship, but it acts as if the ship sign isn’t considered yours anymore. Sometimes when pulled out, it will put you outside the ship. Turning and autopiloting will not teleport the player into the right place, it’s a bit odd and random.

**Comment by GingerWalnut** [comment]
Is that the only time it happens?

**Comment by TiatLief** [comment]
I haven't been able to figure out a cause might be related to player orientation/facing being incorrect sometimes

**Comment by Seamonster778778778788** [comment]
@TiatLief has this happened recently?

**Comment by Seamonster778778778788** [comment]
still happens

**Comment by Seamonster778778778788** [comment]
it appears it is when you get pulled out of slipspace

**Comment by Jarkyc** [comment]
Finally, for the love of god, fixed this.
