### ISSUE TITLE
Can't access Destroyer class while being on Cruiser class level

### ISSUE THREAD

**Issue by BlockBuster019** [GingerWalnut/SQBeyondPublic#461]
![2020-01-05_00 10 18](https://user-images.githubusercontent.com/20263443/71772701-c7d88880-2f4f-11ea-9e76-ff088206edad.png)
![2020-01-05_00 10 19](https://user-images.githubusercontent.com/20263443/71772702-cc04a600-2f4f-11ea-8e34-734e0f2c68b2.png)
I can't access the ship class below the one I unlocked somehow. I ranked up two times in a short amount of time.

**Comment by GingerWalnut** [comment]
FIxed for next restart. Your permissions (and anyone else with the same problems) will need to be fixed manually.
