### ISSUE TITLE
More Sq Tech activating bonuses

### ISSUE THREAD

**Issue by Laserlance141** [GingerWalnut/SQBeyondPublic#47]
A bit related to #38 , but now with the block placer making the MCMMO ore doubling perk go crazy, along with the Defalos ore upgrade perk. I have no idea why the block placer activates this perk, but it also does prove that the block placer does not place the blocks in a way that would prevent the perks from activating again. So basically 2 things, Block placer activates the perks, and also it allows for the perks to be activated.

**Comment by GingerWalnut** [comment]
Fixed
