### ISSUE TITLE
Ship Containers Destroyed

### ISSUE THREAD

**Issue by Masafu** [GingerWalnut/SQBeyondPublic#470]
I was attacked by Johny2268 on Canora, and when my ship regenerated the droppers I had placed inside (2) weren't regenerated, although I had re-detected the ship and had them become part of the ship when I was on Feldost. The crafting table was also not re-generated.

I have not moved the ship or re-piloted it since the incident.

**Comment by APnaptime** [comment]
did you have a ship shield?

**Comment by Masafu** [comment]
Yes, and it is still active

**Comment by APnaptime** [comment]
Weird. If it happens again, let us know how we can reproduce it

**Comment by Masafu** [comment]
Alright, will do. Any chance of a refund, or is that limited to the Refund Discord chat?
