### ISSUE TITLE
Armor Bug

### ISSUE THREAD

**Issue by KingPrussia** [GingerWalnut/SQBeyondPublic#474]
While adding armor to my Blockade runner, after re-detecting i noticed that the Block count and the armor percentage stayed the same. after multiple attempts and adding another stack of stone brick slabs, the armor and block count did not change. Ship is still able to fly.

**Comment by Seamonster778778778788** [comment]
Are you sure you redetected? Could not reproduce. 
![image](https://user-images.githubusercontent.com/34897864/73222638-58f2e780-4129-11ea-9fba-7e8f48d9680b.png)

![image](https://user-images.githubusercontent.com/34897864/73222649-5f815f00-4129-11ea-81e0-160110b028d1.png)

**Comment by Seamonster778778778788** [comment]
Also double check that you arent using carriers.

**Comment by Seamonster778778778788** [comment]
@KingPrussia When possible could you test this again?

**Comment by Seamonster778778778788** [comment]
@KingPrussia

**Comment by Seamonster778778778788** [comment]
please reopen if reoccurs
