### ISSUE TITLE
(lance come here) i didnt finish breaking the rules...

### ISSUE THREAD

**Issue by qq410219243** [GingerWalnut/SQBeyondPublic#479]
(memo: sea and jarkyc please pass this on to lance)
Dear Lance,

You are officially dyslexic.
I said you could **MUTE** me after i finished breaking the rules.
Additionally, I didn't even finish breaking the rules! wtf?
Like, I didn't even break rules #3, 8, 9, and 10. You clearly said rules 1-7 were done. 8-10 + the one I skipped were not.
Unban me so i can finish.

Regards,
Icefurry

**Comment by Jarkyc** [comment]
![DB3A49F8-1EEB-44D5-8651-9D2979603E72](https://user-images.githubusercontent.com/35086102/73417735-2e4e8d80-42e7-11ea-92e7-fb3351deb383.jpeg)

1) use proper ban appeals next time
2) denied

**Comment by qq410219243** [comment]
wait ok i get 1,2 but 3? how long?
