### ISSUE TITLE
Chunk Glitch on Hylon

### ISSUE THREAD

**Issue by NevLo** [GingerWalnut/SQBeyondPublic#48]
![2019-02-25_18 57 10](https://user-images.githubusercontent.com/19544688/53384346-5e4f1d00-392f-11e9-8e62-42f962c1bbab.png)

Glitched chunks at <-2432, 610> on hylon

**Comment by Jarkyc** [comment]
I don’t think that’s a chunk glitch I think that’s where pro thanos snapped hylon

**Comment by GingerWalnut** [comment]
Pro did stuff
