### ISSUE TITLE
space floating not working for some players

### ISSUE THREAD

**Issue by Laserlance141** [GingerWalnut/SQBeyondPublic#480]
Zand_ could not float in space, no idea why, when I set myself to survival and tried the same, i floated, they did not. area was clear other than a noob fighter

**Comment by Seamonster778778778788** [comment]
is there a block above them

**Comment by Seamonster778778778788** [comment]
@Laserlance141

**Comment by Seamonster778778778788** [comment]
no update/and no further cases
