### ISSUE TITLE
chunk issues

### ISSUE THREAD

**Issue by APnaptime** [GingerWalnut/SQBeyondPublic#481]
![2020-02-01_23 11 18](https://user-images.githubusercontent.com/12319920/73604092-8506d200-4548-11ea-80ff-aef57739a3c6.png)

**Comment by MrBarramundi** [comment]
I've noticed some of these as well. I don't mind them but they do look weird.

**Comment by Pairjax** [comment]
Fixed.

**Comment by Pairjax** [comment]
Let me know if this happens again. Is not something that is fixed programming-side, so we just have to manually edit them out. If you do find them, please contribute coordinates.
