### ISSUE TITLE
Tree leaves don't decay

### ISSUE THREAD

**Issue by MrBarramundi** [GingerWalnut/SQBeyondPublic#483]
I've noticed on Avaquo that tree leaves don't decay over time. I would understand the custom trees to do that but the naturally grown trees don't decay either. I've asked in chat every now and then if leaves decay and it seems like they don't decay anywhere. Thank you, Mr. B

**Comment by Seamonster778778778788** [comment]
Tree leaf decay is off because custom tree leaves dont act like they're supposed to so every single leaf on the planet decays and since leaves drop sticks now, it does not bode well for the server
