### ISSUE TITLE
Galactic Council page

### ISSUE THREAD

**Issue by MrBarramundi** [GingerWalnut/SQBeyondPublic#484]
I really like the idea of the Galactic Council but I'm not sure how it works. Can we get the page filled out for it. There is a place holder for it at the bottom of the page but no link. I would imagine this page would explain diplomatic power as well, which I would also like to know how its generated. Like it diplomatic power generated on a town base? Does a nation get more diplomatic power if it has more towns? Is Diplomatic power a local thing so each town has its own power that doesn't contribute to the nation? Thank you, Mr. B

**Comment by fin444** [comment]
https://github.com/GingerWalnut/SQBeyondPublic/wiki/Galactic-Council
Currently a work-in-progress page, but it should be filled up by our collective knowledge soon
