### ISSUE TITLE
Enormous merchant fleet

### ISSUE THREAD

**Issue by Afgncaatp** [GingerWalnut/SQBeyondPublic#487]
There is a continuous stream of merchant ships running thousands of blocks in space. One place you can see it is at 7863, 15122.

**Comment by Seamonster778778778788** [comment]
already known but should be higher priority

**Comment by Seamonster778778778788** [comment]
will be fixed friday

**Comment by Pairjax** [comment]
Fixed. Was not closed prior, but has been fixed for a while.
