### ISSUE TITLE
slipgates and shift flying seems broken

### ISSUE THREAD

**Issue by Corax-ctrl** [GingerWalnut/SQBeyondPublic#489]
shift flying is extremely fast, I'm in a cutter and I just shift flew half way across Usan, along with this, slip-gates don't seem to be functioning or working at all.

**Comment by Corax-ctrl** [comment]
OK, other ship types, at least starfighters, don't seem to be having the shift issue

**Comment by dodopatte** [comment]
I've also experienced this, can confirm

**Comment by dodopatte** [comment]
I wonder if someone fixed it, I went online just now and the shift flying seems good, or at least better.

**Comment by fin444** [comment]
According to what I heard in in-game chat, the shift flying had to do with radar being on your ship, and has now been fixed. I don't know if slipgates have been fixed though

**Comment by fin444** [comment]
I can also confirm that slipgates work, this issue can now be closed.

**Comment by Pairjax** [comment]
Fixed. Closing the issue, thank you.
