### ISSUE TITLE
Dolphins spawn fast and dont stop on Avaquo

### ISSUE THREAD

**Issue by dodopatte** [GingerWalnut/SQBeyondPublic#490]
As the title says, when you approach a body of water on Avaquo dolphins dont stop spawning in stupid numbers, they also make it impossible to play and fly a ship, might be crashing or lagging the server.
I'm attaching a photo of an example.
![dophins](https://user-images.githubusercontent.com/62372259/77038491-aace2600-6992-11ea-93b5-7616d2d12840.PNG)

**Comment by dodopatte** [comment]
![skelly](https://user-images.githubusercontent.com/62372259/77148996-6ebcc300-6a6f-11ea-99f6-13afe54181e1.PNG)
apparently it's a general mob spawning problems, plus this Arenstrad and those are normal skeletons, not strays or zombies.

**Comment by Pairjax** [comment]
Fixed.
