### ISSUE TITLE
Chargers Act a Bit Strangely

### ISSUE THREAD

**Issue by fin444** [GingerWalnut/SQBeyondPublic#496]
First of all, they don't require the sponges in order to work.

Second, mine keeps getting 9 additional charge every time I open the GUI.

**Edit:** In general, how much charge is in a charger is not explained, and coal is consumed seemingly arbitrarily.

**Comment by Afgncaatp** [comment]
Shift clicking items out of a charger, either the sign or the dropper deletes them

**Comment by Afgncaatp** [comment]
Another fun quirk, you can destroy the entire rest of the charger after building it and it still works

**Comment by dodopatte** [comment]
more details on the items disappearing in the charger is that it happen only when you exit the gui and come back, then shift click, otherwise you can shift click or do anything as you want.

**Comment by Griffinwizard** [comment]
All of these were fixed a few days ago.
