### ISSUE TITLE
Crafting levels wildly fluctuating

### ISSUE THREAD

**Issue by Afgncaatp** [GingerWalnut/SQBeyondPublic#497]
![image](https://user-images.githubusercontent.com/8279338/78196966-ae10e980-7449-11ea-8b32-42ade64eec2a.png)
Shift clicking to craft a bunch of planks results in crafting levels going up and down

**Comment by GingerWalnut** [comment]
Pretty sure I remember this one being an April Fools thing for MCMMO. Not sure Crafting is even a real skill.
