### ISSUE TITLE
Suggestion: Better weapons

### ISSUE THREAD

**Issue by Bixloof** [GingerWalnut/SQBeyondPublic#505]
I have played on a lot of move craft theme servers, The server with the best "Gun like" weapons used the crack shot plugin. Its not hard to setup, and works very well as a guns plugin. The current guns in-game are a bit strange and seem old. I simply suggest using this plugin to increase the performance of the server.
-Bixlo

**Comment by Seamonster778778778788** [comment]
already working on this ;)
