### ISSUE TITLE
McMMO Fuel Efficiency Doesn't Work

### ISSUE THREAD

**Issue by fin444** [GingerWalnut/SQBeyondPublic#507]
I have 2x smelting fuel efficiency in McMMO, but 1 coal only smelts 8 items for me instead of 16. I am inserting all items manually without any machines.

**Comment by Seamonster778778778788** [comment]
weird mcmmo bug maybe
might be disabled?

**Comment by Seamonster778778778788** [comment]
enabled, so a bug

**Comment by fin444** [comment]
Apparently it's a feature that this only works for ores? Not really sure why, but not a bug
