### ISSUE TITLE
Beam Transporters are really inconsistent

### ISSUE THREAD

**Issue by fin444** [GingerWalnut/SQBeyondPublic#516]
You have to move around to be able to go up one, they only work a fraction of the time when you're below

**Comment by Laserlance141** [comment]
the fraction of the time might be related to having to click with the clock on open air, if you click a block it does not activate

**Comment by fin444** [comment]
Yup, that is the issue

**Comment by fin444** [comment]
Fixed in next update to the plugin, not sure what restart it'll be applied on
