### ISSUE TITLE
add online check for votifier announcements

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#520]
![image](https://user-images.githubusercontent.com/34897864/80171065-10738a80-85af-11ea-9e88-ea4e3902b08c.png)
![image](https://user-images.githubusercontent.com/34897864/80171079-15d0d500-85af-11ea-932e-3d0720241e4e.png)
to prevent this basically
check if player is online or ever joined before announcing

**Comment by fin444** [comment]
Fixed in latest version, not sure what restart it'll be applied on
