### ISSUE TITLE
Bug: minecarts with tnt do not regen

### ISSUE THREAD

**Issue by Elttob** [GingerWalnut/SQBeyondPublic#53]
Using activator rails and minecarts with tnt, you can make explosions which don't regen. As a control I tested with regular tnt and creepers also, and only the minecart did not regen. Either this is broken or lasts far longer than regular explosions, both of which are concerning.

**Comment by TiatLief** [comment]
They are also rather powerful compared to bomb chutes, and can probably be used for raiding (can be placed outside claim and travel in on rails). Also fairly useable in svs, loading onto a track is just as easy as activating a chute but the minecarts do more dmg and cost tnt+the cart.

**Comment by GingerWalnut** [comment]
This has been fixed
