### ISSUE TITLE
Forge master is facing the wrong way. 

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#62]
https://imgur.com/a/kdtS6KB

**Comment by Jarkyc** [comment]
the npc also is very dark. It was a lighting glitch, so it looks like NPCs are unaffected my lighting glitches

**Comment by Jarkyc** [comment]
Shady Sam also faces the wrong way. Upon further research, it seems that the NPCs that move defauftly face south,

**Comment by GingerWalnut** [comment]
Intended. Side effect of trying to fix the npc bug. I will restore at a later date.
