### ISSUE TITLE
The server won't let me speak

### ISSUE THREAD

**Issue by fiercedude** [GingerWalnut/SQBeyondPublic#64]
A couple times now I've been doing stuff with world edit when suddenly The server wont let me chat anymore, and the only way I can fix it seems to be by re-logging.

**Comment by fiercedude** [comment]
![2019-02-26_17 10 15](https://user-images.githubusercontent.com/19196262/53454439-30cca700-39f5-11e9-8255-70c49508fd22.png)
It sends this message every time I try to chat

**Comment by Jarkyc** [comment]
I think its the anti-spam mute plugin. happened to me too.

**Comment by GingerWalnut** [comment]
I haven't heard any issues about this lately.
