### ISSUE TITLE
SQTech Engines Duplicate fuel when moving

### ISSUE THREAD

**Issue by BundtCake** [GingerWalnut/SQBeyondPublic#65]
![2019-02-26_16 07 43](https://user-images.githubusercontent.com/39447293/53455857-cf024200-39e0-11e9-94ca-7b44c663da8f.png)
Whenever an engine moves, it seems that the contents of its furnaces gets duplicated and dropped on the floor.
Edit: Contents of droppers also get duplicated

**Comment by GingerWalnut** [comment]
Fixed for next restart
