### ISSUE TITLE
faction contracts seem to be tied to the player

### ISSUE THREAD

**Issue by TiatLief** [GingerWalnut/SQBeyondPublic#66]
Made a faction, accepted a contract, disbanded the faction.
Remade the faction and the same contract was still excepted (this might just be due to the name being the same).
Second related issue: accepted mine emeralds contract, mined 4 emeralds, abandoned contract, contract menu showed the same contract with 4/64 even though it was abandoned, reaccepting also kept the progress. Actually, maybe this is intentional but please confirm. If intentional, do contracts reroll every-day or so?

**Comment by TiatLief** [comment]
Definitely bugged in the fact that when I unaccepted it and mined 2 more emerald ores it progress to 6/64. Also happened while having a different contract accepted.

**Comment by TiatLief** [comment]
This also happened to a gold contract in the gui that I don't remember ever accepting.

**Comment by GingerWalnut** [comment]
I think it is probably because the name was the same. I don't think this part is a huge issue. 

Fixed this part for the next restart.
