### ISSUE TITLE
Crashing still occurs. 

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#69]
The crashing when SvSing still occurs, same crash message. 

The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot get property bme{name=facing, clazz=class eq, values=[north, south, west, east]} as it does not exist in Block{minecraft:dispenser}

It’s tile and storage entities I think. It always happens with droppers dispensers and hoppers.

**Comment by GingerWalnut** [comment]
What version of MC are you using?

**Comment by Jarkyc** [comment]
1.13.2. That’s the only version that works on the server right?

**Comment by GingerWalnut** [comment]
I think I finally found the issue. It should be fixed for the next restart.
