### ISSUE TITLE
Can get stuck in elevator if there is a block in the way.

### ISSUE THREAD

**Issue by TiatLief** [GingerWalnut/SQBeyondPublic#78]
"Can't leave elevator in use"
Elevator was built before blocks in the way were placed.
Blocks in question were 3 glass in a row.

**Comment by Jarkyc** [comment]
Lifts isn’t our plugin, we have no control over this.

**Comment by TiatLief** [comment]
same as other elevator bug, pretty sure ginger rewrote lift

**Comment by Jarkyc** [comment]
Made sure to run it by ginger before putting the wontfix. We have a public version of lift, it isn't our plugin. If it was rewritten it was never brought over to beyond.

**Comment by GingerWalnut** [comment]
We did write our own plugin for 5.0, but it was in Sponge so I couldn't bring it over.
