### ISSUE TITLE
You can break certain blocks on piloted ships

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#8]
I don't know which blocks specifically, but my class keeps breaking while my ship is piloted and i left click to fire my cannons.

**Comment by Jarkyc** [comment]
It stopped doing it so i dont know how to cause it

**Comment by GingerWalnut** [comment]
What exactly happened?

**Comment by Jarkyc** [comment]
> What exactly happened?

so i think that once you redetect a ship it lets you pilot it for a bit and that is what was hapening. Because then I looked in the ship sign and it said I wasn't even piloting.

**Comment by GingerWalnut** [comment]
There was a bug with re-detecting that has been fixed. This probably was fixed as well.
