### ISSUE TITLE
items disappearing from hoppers part of slipdrive multiblock

### ISSUE THREAD

**Issue by TiatLief** [GingerWalnut/SQBeyondPublic#82]
Haven't been able to find the cause, I specifically tested shifting, autopilot, and the slipdrive before/after use.

**Comment by TiatLief** [comment]
Ok this is really weird, any items put in the dropper disappear if you shift fly in the direction the hopper is facing

**Comment by TiatLief** [comment]
doesn't effect droppers

**Comment by TiatLief** [comment]
does not happen when there is only a single hopper, can't test further due to dropper limitation (previously happened when a hopper was part of a slipdrive)

**Comment by GingerWalnut** [comment]
Fixed for next restart
