### ISSUE TITLE
Suggestion: Recipe for sponge

### ISSUE THREAD

**Issue by Jarkyc** [GingerWalnut/SQBeyondPublic#86]
Add a recipe for sponge that involves like iron and redstone or something (since it’s the Mechanical Blocks). Also maybe add them on one of the moons to be harvested?

**Comment by Elttob** [comment]
I believe that sponge is only intended to be gained through voting, that's how we've done it historically.

**Comment by GingerWalnut** [comment]
Voting will remain the only way to get sponges for the immediate future. I might end up increasing the amount you get though.
