### ISSUE TITLE
Sitting on slabs gets you stuck on autopilot

### ISSUE THREAD

**Issue by Creepopolous** [GingerWalnut/SQBeyondPublic#99]
If you were to sit on the slabs on top of your ship, you would be left behind when your ship is on autopilot. Eventually, the ship would be too far away and you are forced to exit it. The game still has the arrow or whatever it uses to make you sit on the slab in the same position before it jumped. Meaning that if you are on a planet, you will fall when you dismount or log out and log back in. When you manually shift, you dismount, and still have control of the ship.

**Comment by n0807701j2d2** [comment]
Yeah I was chasing someone and right clicked on the slab. I fell off the ship and it unpiloted, so I lost 'em. Dang!

-Wine_Craft

**Comment by GingerWalnut** [comment]
Fixed for next restart
